# Topic Modeling
## This notebook outlines the concepts involved in Topic Modeling


Topic modeling is a statistical model to **discover** the abstract "topics" that occur in a collection of documents

It is commonly used in text document. But nowadays, in social media analysis, topic modeling is an emerging research area.

One of the most popular algorithms used is **Latent Dirichlet Allocation** which was proposed by
David Blei et al in 2003.

Dataset:
https://raw.githubusercontent.com/subashgandyer/datasets/main/kaggledatasets.csv

### Steps
- Install the necessary library
- Import the necessary libraries
- Download the dataset
- Load the dataset
- Pre-process the dataset
    - Tokenize
    - Stop words removal
    - Non-alphabetic words removal
    - Lowercase
- Create a dictionary for the document
- Filter low frequency words
- Create an Index to word dictionary
- Train the Topic Model
- Predict on the dataset
- Visualize the topics

### Install the necessary library

In [ ]:
%%capture
! pip install gensim

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

### Import the necessary libraries

In [ ]:
from pprint import pprint

import pandas as pd

import gensim
from gensim import corpora, models
from gensim.models import LdaModel
from gensim.corpora import Dictionary

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
from nltk.stem.wordnet import WordNetLemmatizer

nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

### Download the dataset

In [ ]:
!wget https://raw.githubusercontent.com/subashgandyer/datasets/main/kaggledatasets.csv

--2025-11-04 02:09:33--  https://raw.githubusercontent.com/subashgandyer/datasets/main/kaggledatasets.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3881130 (3.7M) [text/plain]
Saving to: ‘kaggledatasets.csv.1’

kaggledatasets.csv. 100%[===================>]   3.70M  --.-KB/s    in 0.09s

2025-11-04 02:09:33 (39.8 MB/s) - ‘kaggledatasets.csv.1’ saved [3881130/3881130]

### Load the dataset

In [ ]:
df = pd.read_csv("kaggledatasets.csv")
df.head()

,Title,Subtitle,Owner,Votes,Versions,Tags,Data Type,Size,License,Views,Download,Kernels,Topics,URL,Description
0,Credit Card Fraud Detection,Anonymized credit card transactions labeled as...,Machine Learning Group - ULB,1241,"Version 2,2016-11-05|Version 1,2016-11-03",crime\nfinance,CSV,144 MB,ODbL,"442,136 views","53,128 downloads","1,782 kernels",26 topics,https://www.kaggle.com/mlg-ulb/creditcardfraud,The datasets contains transactions made by cre...
1,European Soccer Database,"25k+ matches, players & teams attributes for E...",Hugo Mathien,1046,"Version 10,2016-10-24|Version 9,2016-10-24|Ver...",association football\neurope,SQLite,299 MB,ODbL,"396,214 views","46,367 downloads","1,459 kernels",75 topics,https://www.kaggle.com/hugomathien/soccer,The ultimate Soccer database for data analysis...
2,TMDB 5000 Movie Dataset,"Metadata on ~5,000 movies from TMDb",The Movie Database (TMDb),1024,"Version 2,2017-09-28",film,CSV,44 MB,Other,"446,255 views","62,002 downloads","1,394 kernels",46 topics,https://www.kaggle.com/tmdb/tmdb-movie-metadata,Background\nWhat can we say about the success ...
3,Global Terrorism Database,"More than 170,000 terrorist attacks worldwide,...",START Consortium,789,"Version 2,2017-07-19|Version 1,2016-12-08",crime\nterrorism\ninternational relations,CSV,144 MB,Other,"187,877 views","26,309 downloads",608 kernels,11 topics,https://www.kaggle.com/START-UMD/gtd,"Context\nInformation on more than 170,000 Terr..."
4,Bitcoin Historical Data,Bitcoin data at 1-min intervals from select ex...,Zielak,618,"Version 11,2018-01-11|Version 10,2017-11-17|Ve...",history\nfinance,CSV,119 MB,CC4,"146,734 views","16,868 downloads",68 kernels,13 topics,https://www.kaggle.com/mczielinski/bitcoin-his...,Context\nBitcoin is the longest running and mo...

### Explore the dataset

In [ ]:
df.columns

Index(['Title', 'Subtitle', 'Owner', 'Votes', 'Versions', 'Tags', 'Data Type',
       'Size', 'License', 'Views', 'Download', 'Kernels', 'Topics', 'URL',
       'Description'],
      dtype='object')

In [ ]:
df.dtypes

Title          object
Subtitle       object
Owner          object
Votes           int64
Versions       object
Tags           object
Data Type      object
Size           object
License        object
Views          object
Download       object
Kernels        object
Topics         object
URL            object
Description    object
dtype: object

In [ ]:
df['Description'].iloc[0]

"The datasets contains transactions made by credit cards in September 2013 by european cardholders. This dataset presents transactions that occurred in two days, where we have 492 frauds out of 284,807 transactions. The dataset is highly unbalanced, the positive class (frauds) account for 0.172% of all transactions.\nIt contains only numerical input variables which are the result of a PCA transformation. Unfortunately, due to confidentiality issues, we cannot provide the original features and more background information about the data. Features V1, V2, ... V28 are the principal components obtained with PCA, the only features which have not been transformed with PCA are 'Time' and 'Amount'. Feature 'Time' contains the seconds elapsed between each transaction and the first transaction in the dataset. The feature 'Amount' is the transaction Amount, this feature can be used for example-dependant cost-senstive learning. Feature 'Class' is the response variable and it takes value 1 in case of fraud and 0 otherwise.\nGiven the class imbalance ratio, we recommend measuring the accuracy using the Area Under the Precision-Recall Curve (AUPRC). Confusion matrix accuracy is not meaningful for unbalanced classification.\nThe dataset has been collected and analysed during a research collaboration of Worldline and the Machine Learning Group (http://mlg.ulb.ac.be) of ULB (Université Libre de Bruxelles) on big data mining and fraud detection. More details on current and past projects on related topics are available on http://mlg.ulb.ac.be/BruFence and http://mlg.ulb.ac.be/ARTML\nPlease cite: Andrea Dal Pozzolo, Olivier Caelen, Reid A. Johnson and Gianluca Bontempi. Calibrating Probability with Undersampling for Unbalanced Classification. In Symposium on Computational Intelligence and Data Mining (CIDM), IEEE, 2015"

In [ ]:
df.isnull().sum()

Title            0
Subtitle       104
Owner            0
Votes            0
Versions         5
Tags           542
Data Type        0
Size             0
License          0
Views            5
Download        15
Kernels        944
Topics         592
URL              0
Description      5
dtype: int64

### Extract the data for topic modeling

In [ ]:
for i in df['Description'].items():
    raw = str(i[1]).lower()
    print(raw)

Output hidden; open in https://colab.research.google.com to view.

### Pre-process the dataset
- Tokenize
- Stop words removal
- Non-alphabetic words removal
- Lowercase
- Define them

### Define the pattern, tokenizer, stop words and lemmatizer

In [ ]:
pattern = r'\b[^\d\W]+\b'
tokenizer = RegexpTokenizer(pattern)
en_stop = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

### Preprocess

In [ ]:
texts = []

for idx, desc in df['Description'].items():
    # clean and tokenize document string
    raw_text = str(desc).lower()
    tokens = tokenizer.tokenize(raw_text)

    # remove stop words
    stopped_tokens = [t for t in tokens if t not in en_stop]

    # lemmatize tokens
    lemma_tokens = [lemmatizer.lemmatize(t) for t in stopped_tokens]

    # remove single-character words
    filtered_tokens = [t for t in lemma_tokens if len(t) > 1]

    # add tokens to list
    texts.append(filtered_tokens)

# check one example
print(texts[0])

['datasets', 'contains', 'transaction', 'made', 'credit', 'card', 'september', 'european', 'cardholder', 'dataset', 'present', 'transaction', 'occurred', 'two', 'day', 'fraud', 'transaction', 'dataset', 'highly', 'unbalanced', 'positive', 'class', 'fraud', 'account', 'transaction', 'contains', 'numerical', 'input', 'variable', 'result', 'pca', 'transformation', 'unfortunately', 'due', 'confidentiality', 'issue', 'cannot', 'provide', 'original', 'feature', 'background', 'information', 'data', 'feature', 'principal', 'component', 'obtained', 'pca', 'feature', 'transformed', 'pca', 'time', 'amount', 'feature', 'time', 'contains', 'second', 'elapsed', 'transaction', 'first', 'transaction', 'dataset', 'feature', 'amount', 'transaction', 'amount', 'feature', 'used', 'example', 'dependant', 'cost', 'senstive', 'learning', 'feature', 'class', 'response', 'variable', 'take', 'value', 'case', 'fraud', 'otherwise', 'given', 'class', 'imbalance', 'ratio', 'recommend', 'measuring', 'accuracy', 'using', 'area', 'precision', 'recall', 'curve', 'auprc', 'confusion', 'matrix', 'accuracy', 'meaningful', 'unbalanced', 'classification', 'dataset', 'collected', 'analysed', 'research', 'collaboration', 'worldline', 'machine', 'learning', 'group', 'http', 'mlg', 'ulb', 'ac', 'ulb', 'université', 'libre', 'de', 'bruxelles', 'big', 'data', 'mining', 'fraud', 'detection', 'detail', 'current', 'past', 'project', 'related', 'topic', 'available', 'http', 'mlg', 'ulb', 'ac', 'brufence', 'http', 'mlg', 'ulb', 'ac', 'artml', 'please', 'cite', 'andrea', 'dal', 'pozzolo', 'olivier', 'caelen', 'reid', 'johnson', 'gianluca', 'bontempi', 'calibrating', 'probability', 'undersampling', 'unbalanced', 'classification', 'symposium', 'computational', 'intelligence', 'data', 'mining', 'cidm', 'ieee']

### Create a dictionary

In [61]:
dictionary = Dictionary(texts)
dictionary[1]

'account'

### Filter low frequency words

In [ ]:
dictionary.filter_extremes(no_below=10, no_above=0.5)
# convert tokenized documents into a document-term matrix
corpus = [dictionary.doc2bow(text) for text in texts]
print(corpus)

[[(0, 3), (1, 1), (2, 2), (3, 3), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1), (12, 3), (13, 2), (14, 1), (15, 1), (16, 1), (17, 1), (18, 3), (19, 1), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 7), (31, 1), (32, 4), (33, 1), (34, 1), (35, 1), (36, 3), (37, 1), (38, 1), (39, 1), (40, 1), (41, 1), (42, 2), (43, 1), (44, 1), (45, 1), (46, 1), (47, 1), (48, 2), (49, 1), (50, 1), (51, 1), (52, 1), (53, 1), (54, 1), (55, 1), (56, 1), (57, 1), (58, 1), (59, 1), (60, 1), (61, 1), (62, 1), (63, 1), (64, 1), (65, 1), (66, 1), (67, 1), (68, 1), (69, 1), (70, 1), (71, 1), (72, 1), (73, 1), (74, 2), (75, 1), (76, 7), (77, 1), (78, 1), (79, 1), (80, 1), (81, 1), (82, 1), (83, 1), (84, 2)], [(9, 1), (10, 1), (12, 2), (23, 1), (28, 1), (30, 1), (31, 1), (36, 3), (42, 1), (43, 1), (52, 2), (55, 3), (57, 1), (60, 2), (61, 1), (74, 2), (82, 2), (83, 1), (85, 2), (86, 2), (87, 1), (88, 1), (89, 1), (90, 1), (91, 3), (92, 1), (93, 1), (94, 1), (95, 1), (96, 1), (97, 5), (98, 1), (99, 1), (100, 1), (101, 4), (102, 1), (103, 1), (104, 1), (105, 1), (106, 2), (107, 1), (108, 1), (109, 1), (110, 3), (111, 1), (112, 1), (113, 1), (114, 1), (115, 1), (116, 1), (117, 1), (118, 1), (119, 1), (120, 1), (121, 2), (122, 1), (123, 1), (124, 2), (125, 1), (126, 1), (127, 2), (128, 1), (129, 1), (130, 1), (131, 1), (132, 1), (133, 1), (134, 3), (135, 1), (136, 1), (137, 1), (138, 1), (139, 1), (140, 6), (141, 1), (142, 1), (143, 2), (144, 2), (145, 3), (146, 1), (147, 8), (148, 3), (149, 1), (150, 1), (151, 1), (152, 1), (153, 1), (154, 1), (155, 3), (156, 1), (157, 1), (158, 1), (159, 1), (160, 1), (161, 1), (162, 1), (163, 1), (164, 2), (165, 1), (166, 1), (167, 1), (168, 1), (169, 2), (170, 2), (171, 1), (172, 2), (173, 1), (174, 1), (175, 1), (176, 3), (177, 1), (178, 2), (179, 5), (180, 2), (181, 1), (182, 1), (183, 1), (184, 1), (185, 1), (186, 2), (187, 1), (188, 2), (189, 1), (190, 1), (191, 1), (192, 6), (193, 1), (194, 1), (195, 1), (196, 1), (197, 1), (198, 1), (199, 1), (200, 8), (201, 1), (202, 1), (203, 1), (204, 1), (205, 1), (206, 1), (207, 1), (208, 1), (209, 1), (210, 1), (211, 1), (212, 1), (213, 1), (214, 3), (215, 1), (216, 1), (217, 2), (218, 1), (219, 2), (220, 1), (221, 3), (222, 2), (223, 1), (224, 4), (225, 1), (226, 1), (227, 8), (228, 1), (229, 1), (230, 1), (231, 1), (232, 1), (233, 1), (234, 1), (235, 1), (236, 1), (237, 1), (238, 2), (239, 1), (240, 1), (241, 1), (242, 1), (243, 1), (244, 1), (245, 1), (246, 4), (247, 1), (248, 1), (249, 1)], [(6, 1), (18, 1), (20, 4), (21, 1), (25, 1), (29, 5), (31, 2), (33, 1), (34, 1), (35, 1), (38, 1), (52, 3), (55, 1), (74, 2), (79, 1), (81, 1), (83, 1), (85, 1), (86, 2), (88, 1), (91, 2), (92, 2), (93, 4), (109, 3), (112, 1), (114, 1), (124, 2), (127, 1), (135, 2), (141, 2), (156, 1), (157, 1), (164, 1), (168, 5), (170, 1), (174, 2), (175, 1), (180, 1), (181, 3), (186, 5), (196, 1), (201, 1), (205, 1), (221, 2), (231, 1), (232, 1), (238, 1), (247, 1), (250, 1), (251, 3), (252, 1), (253, 2), (254, 2), (255, 1), (256, 1), (257, 2), (258, 5), (259, 1), (260, 1), (261, 3), (262, 1), (263, 1), (264, 1), (265, 1), (266, 1), (267, 1), (268, 1), (269, 1), (270, 2), (271, 1), (272, 1), (273, 1), (274, 1), (275, 1), (276, 1), (277, 1), (278, 1), (279, 1), (280, 1), (281, 2), (282, 1), (283, 1), (284, 1), (285, 1), (286, 1), (287, 1), (288, 1), (289, 4), (290, 1), (291, 1), (292, 1), (293, 9), (294, 1), (295, 1), (296, 1), (297, 1), (298, 1), (299, 2), (300, 2), (301, 1), (302, 1), (303, 1), (304, 2), (305, 1), (306, 2), (307, 1), (308, 1), (309, 1), (310, 1), (311, 1), (312, 5), (313, 1), (314, 1), (315, 1), (316, 1), (317, 1), (318, 1), (319, 1), (320, 1), (321, 1), (322, 1), (323, 1), (324, 1), (325, 1), (326, 1), (327, 2), (328, 1), (329, 1), (330, 1), (331, 1), (332, 1), (333, 2), (334, 1), (335, 1), (336, 1), (337, 1), (338, 6), (339, 1), (340, 1), (341, 2), (342, 1), (343, 1), (344, 1), (345, 1), (346, 4), (347, 1), (348, 2), (349, 1), (350, 1), (351, 2), (352, 1), (353, 1), (354, 1), (355, 1), (356, 1), (357, 1), (358, 1), (359, 1), (360, 3), (361, 1), (362, 1), (363, 1), (364, 1), (365, 1), (366, 1), (367, 5), (368, 1), (369, 1), (370, 1), (371, 1), (372, 1), (373, 1), (374, 2), (375, 4), (376, 2), (377, 1), (378, 1), (379, 1), (380, 1), (381, 2), (382, 1), (383, 1), (384, 1), (385, 2), (386, 1), (387, 1), (388, 1), (389, 1), (390, 1), (391, 1), (392, 2), (393, 1), (394, 1), (395, 1), (396, 1), (397, 4), (398, 1), (399, 1), (400, 1), (401, 1), (402, 2)], [(1, 1), (5, 1), (8, 1), (10, 1), (13, 1), (25, 1), (31, 1), (36, 1), (38, 4), (44, 1), (51, 1), (55, 1), (58, 1), (59, 1), (68, 4), (69, 2), (74, 4), (81, 1), (82, 1), (84, 2), (86, 5), (92, 2), (108, 7), (110, 1), (112, 2), (124, 10), (134, 2), (141, 1), (151, 1), (157, 2), (162, 2), (167, 1), (180, 4), (185, 4), (186, 1), (187, 1), (194, 1), (196, 1), (198, 2), (211, 6), (216, 1), (217, 1), (221, 3), (222, 1), (227, 1), (236, 1), (238, 4), (244, 2), (249, 1), (250, 1), (251, 1), (252, 1), (281, 2), (291, 1), (295, 1), (301, 1), (304, 7), (321, 1), (335, 2), (340, 1), (345, 2), (348, 1), (358, 2), (360, 2), (364, 1), (373, 2), (382, 15), (386, 1), (387, 3), (395, 1), (396, 10), (403, 1), (404, 1), (405, 1), (406, 2), (407, 2), (408, 1), (409, 3), (410, 1), (411, 1), (412, 1), (413, 2), (414, 1), (415, 2), (416, 1), (417, 1), (418, 1), (419, 3), (420, 1), (421, 1), (422, 1), (423, 1), (424, 1), (425, 1), (426, 1), (427, 1), (428, 1), (429, 1), (430, 1), (431, 1), (432, 1), (433, 3), (434, 1), (435, 1), (436, 4), (437, 1), (438, 1), (439, 1), (440, 1), (441, 1), (442, 1), (443, 1), (444, 1), (445, 3), (446, 2), (447, 4), (448, 1), (449, 1), (450, 1), (451, 1), (452, 1), (453, 1), (454, 1), (455, 1), (456, 1), (457, 1), (458, 1), (459, 1), (460, 1), (461, 1), (462, 1), (463, 1), (464, 1), (465, 1), (466, 1), (467, 1), (468, 2), (469, 1), (470, 1), (471, 1), (472, 1), (473, 1), (474, 1), (475, 1), (476, 1), (477, 1), (478, 1), (479, 1), (480, 2), (481, 1), (482, 1), (483, 1), (484, 1), (485, 1), (486, 1), (487, 2), (488, 3), (489, 3), (490, 1), (491, 3), (492, 2), (493, 1), (494, 1), (495, 1), (496, 1), (497, 1), (498, 1), (499, 1), (500, 1), (501, 1), (502, 1), (503, 2), (504, 1), (505, 2), (506, 1), (507, 2), (508, 3), (509, 1), (510, 1), (511, 1), (512, 1), (513, 2), (514, 1), (515, 3), (516, 2), (517, 1), (518, 1), (519, 2), (520, 1), (521, 1), (522, 3), (523, 3), (524, 2), (525, 2), (526, 3), (527, 1), (528, 1), (529, 1), (530, 1), (531, 3), (532, 1), (533, 1), (534, 1), (535, 1), (536, 2), (537, 4), (538, 1), (539, 1), (540, 2), (541, 1), (542, 1), (543, 2), (544, 1), (545, 1), (546, 1), (547, 3), (548, 1), (549, 1), (550, 2), (551, 2), (552, 1), (553, 1), (554, 1), (555, 1), (556, 1), (557, 1), (558, 1), (559, 1), (560, 3), (561, 1), (562, 1), (563, 1), (564, 1), (565, 5), (566, 5), (567, 1), (568, 4), (569, 1), (570, 1), (571, 1), (572, 18), (573, 1), (574, 3), (575, 1), (576, 1), (577, 1), (578, 3), (579, 3), (580, 1), (581, 1), (582, 2), (583, 1), (584, 3), (585, 1), (586, 3), (587, 1), (588, 2), (589, 4), (590, 1)], [(31, 2), (44, 1), (48, 1), (51, 1), (61, 1), (73, 1), (74, 3), (76, 4), (91, 1), (93, 2), (141, 1), (146, 1), (148, 1), (154, 1), (164, 1), (166, 1), (174, 2), (180, 1), (181, 1), (190, 1), (212, 1), (216, 1), (221, 1), (236, 1), (266, 1), (271, 1), (272, 1), (281, 1), (284, 1), (289, 1), (291, 1), (316, 1), (345, 2), (348, 1), (355, 1), (364, 1), (373, 1), (425, 1), (434, 1), (451, 1), (460, 1), (463, 1), (508, 1), (525, 1), (536, 2), (557, 1), (581, 1), (585, 2), (588, 2), (591, 1), (592, 1), (593, 1), (594, 1), (595, 9), (596, 2), (597, 1), (598, 1), (599, 1), (600, 1), (601, 1), (602, 1), (603, 5), (604, 2), (605, 1), (606, 1), (607, 1), (608, 6), (609, 1), (610, 1), (611, 1), (612, 1), (613, 1), (614, 1), (615, 1), (616, 1), (617, 1), (618, 1), (619, 1), (620, 1), (621, 1), (622, 2), (623, 2), (624, 1), (625, 1), (626, 1), (627, 1), (628, 1), (629, 2), (630, 2), (631, 2), (632, 1), (633, 1), (634, 1), (635, 1), (636, 1), (637, 1), (638, 2), (639, 1), (640, 1), (641, 1), (642, 1), (643, 2), (644, 1), (645, 1), (646, 1), (647, 1), (648, 1), (649, 1), (650, 1), (651, 1), (652, 1), (653, 1), (654, 2), (655, 1), (656, 1), (657, 2), (658, 1), (659, 1), (660, 1), (661, 1), (662, 2), (663, 1), (664, 1)], [(23, 2), (31, 3), (34, 1), (42, 4), (43, 3), (54, 1), (62, 1), (66, 2), (68, 8), (71, 1), (74, 3), (81, 2), (88, 2), (92, 1), (95, 1), (102, 1), (109, 5), (111, 1), (118, 2), (127, 1), (138, 1), (150, 1), (153, 1), (164, 1), (168, 4), (169, 1), (174, 1), (179, 1), (186, 1), (193, 1), (225, 1), (247, 1), (253, 1), (266, 1), (278, 1), (280, 1), (289, 1), (291, 6), (297, 1), (298, 1), (315, 2), (321, 5), (328, 1), (345, 1), (360, 14), (372, 1), (383, 1), (396, 2), (412, 6), (416, 3), (420, 2), (425, 1), (434, 1), (464, 2), (488, 2), (495, 1), (508, 1), (509, 1), (514, 1), (515, 1), (544, 2), (555, 7), (557, 2), (562, 1), (566, 2), (582, 1), (586, 1), (587, 1), (603, 11), (604, 2), (608, 1), (631, 1), (647, 1), (649, 1), (652, 1), (655, 1), (661, 1), (665, 1), (666, 1), (667, 1), (668, 1), (669, 1), (670, 2), (671, 1), (672, 1), (673, 2), (674, 3), (675, 1), (676, 1), (677, 1), (678, 2), (679, 1), (680, 1), (681, 1), (682, 1), (683, 1), (684, 1), (685, 1), (686, 1), (687, 2), (688, 2), (689, 1), (690, 1), (691, 1), (692, 1), (693, 1), (694, 1), (695, 1), (696, 1), (697, 1), (698, 1), (699, 1), (700, 2), (701, 3), (702, 1), (703, 1), (704, 2), (705, 1), (706, 1), (707, 1), (708, 1), (709, 1), (710, 1), (711, 2), (712, 1), (713, 1), (714, 4), (715, 1), (716, 1), (717, 1), (718, 12), (719, 3), (720, 2), (721, 1), (722, 2), (723, 1), (724, 1), (725, 2), (726, 1), (727, 4), (728, 12), (729, 1), (730, 2), (731, 1), (732, 1), (733, 2), (734, 2), (735, 1), (736, 1), (737, 1), (738, 1), (739, 1), (740, 1)], [(42, 1), (43, 1), (79, 2), (81, 1), (91, 1), (109, 1), (193, 1), (206, 1), (238, 1), (298, 1), (311, 1), (390, 1), (488, 1), (585, 1), (701, 1), (741, 1), (742, 1), (743, 1), (744, 1), (745, 1), (746, 1), (747, 3), (748, 1)], [(5, 3), (29, 1), (78, 1), (118, 3), (173, 1), (271, 1), (291, 1), (310, 1), (328, 2), (334, 1), (389, 1), (411, 1), (414, 2), (458, 1), (488, 1), (589, 4), (749, 1), (750, 1), (751, 1), (752, 1), (753, 2), (754, 1), (755, 1), (756, 3), (757, 1), (758, 1)], [(13, 1), (31, 2), (42, 1), (44, 1), (55, 2), (62, 1), (70, 2), (79, 4), (81, 1), (83, 2), (90, 1), (91, 1), (109, 5), (130, 1), (146, 1), (156, 1), (174, 1), (175, 1), (178, 1), (193, 1), (197, 1), (203, 1), (216, 1), (238, 2), (291, 1), (295, 1), (322, 2), (325, 2), (341, 5), (360, 1), (373, 2), (388, 1), (390, 1), (396, 1), (414, 1), (421, 1), (431, 1), (437, 1), (471, 2), (574, 1), (584, 1), (598, 2), (600, 1), (603, 4), (616, 1), (618, 1), (629, 1), (649, 3), (657, 1), (673, 2), (688, 1), (708, 2), (727, 1), (759, 1), (760, 1), (761, 1), (762, 1), (763, 1), (764, 1), (765, 1), (766, 1), (767, 1), (768, 2), (769, 1), (770, 4), (771, 1), (772, 1), (773, 1), (774, 1), (775, 2), (776, 1), (777, 1), (778, 1), (779, 4), (780, 2), (781, 1), (782, 1), (783, 1), (784, 1), (785, 1), (786, 1), (787, 2), (788, 1), (789, 2), (790, 1), (791, 2), (792, 2), (793, 1), (794, 1), (795, 1), (796, 1), (797, 2), (798, 1), (799, 1), (800, 2), (801, 1), (802, 1), (803, 1)], [(8, 1), (9, 1), (12, 1), (29, 2), (31, 2), (42, 3), (43, 3), (70, 1), (79, 2), (81, 2), (84, 2), (91, 1), (97, 1), (99, 4), (110, 1), (111, 1), (117, 1), (124, 1), (127, 1), (141, 1), (147, 2), (150, 1), (162, 2), (193, 1), (226, 1), (232, 8), (238, 1), (262, 1), (301, 1), (307, 1), (311, 1), (318, 1), (339, 2), (360, 1), (373, 1), (374, 1), (400, 2), (419, 12), (422, 1), (442, 4), (488, 1), (516, 1), (567, 1), (702, 3), (732, 1), (757, 1), (804, 1), (805, 1), (806, 1), (807, 3), (808, 1), (809, 1), (810, 2), (811, 1), (812, 1), (813, 1), (814, 1), (815, 1), (816, 1), (817, 1), (818, 1), (819, 2), (820, 1), (821, 14), (822, 1), (823, 1), (824, 2), (825, 1), (826, 5), (827, 2), (828, 2), (829, 1), (830, 1), (831, 1), (832, 1)], [(18, 1), (20, 1), (21, 2), (30, 1), (38, 1), (45, 1), (58, 1), (84, 1), (108, 1), (114, 1), (133, 1), (161, 1), (162, 2), (213, 1), (252, 1), (266, 1), (271, 1), (291, 4), (355, 1), (372, 1), (383, 1), (389, 1), (407, 1), (434, 2), (516, 1), (566, 1), (708, 1), (777, 1), (833, 1), (834, 1), (835, 1), (836, 1), (837, 1), (838, 2), (839, 1), (840, 1), (841, 6), (842, 1), (843, 1), (844, 1), (845, 1), (846, 1), (847, 1)], [(4, 2), (15, 1), (18, 1), (19, 1), (30, 1), (31, 1), (41, 1), (42, 1), (44, 2), (55, 2), (66, 1), (74, 1), (81, 1), (82, 1), (83, 1), (85, 1), (91, 1), (92, 1), (108, 1), (117, 3), (118, 2), (133, 1), (150, 1), (151, 1), (156, 2), (164, 1), (165, 1), (166, 1), (174, 1), (176, 1), (178, 1), (201, 1), (213, 1), (223, 2), (229, 1), (232, 1), (236, 1), (238, 1), (266, 1), (281, 1), (289, 1), (298, 1), (307, 1), (316, 1), (343, 1), (360, 1), (361, 1), (370, 1), (384, 1), (391, 3), (396, 1), (400, 1), (407, 1), (414, 1), (421, 2), (493, 1), (502, 1), (516, 1), (542, 3), (566, 2), (587, 2), (614, 1), (636, 1), (702, 3), (704, 1), (735, 1), (771, 1), (772, 4), (776, 1), (799, 1), (803, 1), (820, 2), (848, 2), (849, 1), (850, 1), (851, 2), (852, 1), (853, 1), (854, 1), (855, 1), (856, 1), (857, 2), (858, 3), (859, 3), (860, 1), (861, 2), (862, 6), (863, 1), (864, 1), (865, 1), (866, 1), (867, 2), (868, 1), (869, 3), (870, 2), (871, 3), (872, 5), (873, 2), (874, 1), (875, 2), (876, 1), (877, 1), (878, 1), (879, 2), (880, 1), (881, 1), (882, 2), (883, 1), (884, 1), (885, 3), (886, 3), (887, 1), (888, 19), (889, 1)], [(3, 1), (15, 1), (29, 1), (33, 1), (74, 3), (77, 1), (82, 1), (91, 1), (98, 1), (111, 1), (118, 2), (135, 1), (161, 2), (166, 1), (185, 1), (197, 1), (217, 1), (221, 1), (233, 1), (238, 1), (256, 1), (266, 1), (283, 1), (291, 2), (304, 11), (321, 1), (333, 1), (334, 1), (370, 2), (373, 2), (374, 1), (382, 1), (390, 1), (414, 4), (421, 1), (427, 1), (430, 1), (432, 1), (520, 1), (539, 1), (544, 1), (554, 1), (557, 1), (566, 1), (568, 2), (575, 2), (582, 1), (603, 5), (619, 1), (622, 4), (630, 1), (633, 1), (655, 2), (687, 1), (709, 1), (742, 1), (757, 1), (761, 9), (770, 1), (789, 1), (813, 1), (842, 2), (843, 1), (890, 1), (891, 1), (892, 1), (893, 1), (894, 1), (895, 1), (896, 4), (897, 1), (898, 1), (899, 2), (900, 1), (901, 3), (902, 1), (903, 1), (904, 1), (905, 4), (906, 1), (907, 1), (908, 3), (909, 1), (910, 1), (911, 1), (912, 1), (913, 1), (914, 17), (915, 1), (916, 1), (917, 2), (918, 1), (919, 1), (920, 2), (921, 1), (922, 1), (923, 1), (924, 1), (925, 5), (926, 1), (927, 1), (928, 1), (929, 1), (930, 1), (931, 1), (932, 18), (933, 1), (934, 1), (935, 2)], [(18, 1), (38, 1), (44, 1), (82, 1), (109, 1), (118, 2), (124, 4), (141, 1), (174, 1), (178, 1), (226, 1), (238, 1), (266, 1), (317, 1), (325, 3), (345, 6), (357, 5), (414, 1), (431, 1), (434, 1), (469, 4), (472, 1), (515, 1), (536, 1), (566, 1), (589, 1), (603, 2), (687, 2), (688, 1), (727, 1), (736, 1), (848, 1), (883, 56), (899, 1), (936, 1), (937, 1), (938, 1), (939, 1), (940, 1), (941, 1), (942, 1), (943, 1), (944, 1), (945, 1), (946, 2), (947, 6), (948, 1), (949, 103), (950, 1), (951, 1), (952, 1), (953, 1), (954, 1), (955, 1), (956, 1), (957, 2), (958, 1), (959, 1), (960, 1), (961, 1), (962, 1), (963, 1)], [(38, 1), (50, 1), (127, 1), (161, 1), (167, 1), (170, 1), (171, 1), (172, 1), (199, 1), (216, 1), (232, 3), (333, 3), (336, 1), (337, 1), (339, 1), (375, 3), (421, 1), (425, 1), (542, 2), (566, 1), (570, 1), (697, 1), (720, 8), (721, 1), (728, 2), (803, 4), (869, 1), (915, 1), (964, 1), (965, 1), (966, 1), (967, 1), (968, 1), (969, 1), (970, 1), (971, 5), (972, 2), (973, 1), (974, 1), (975, 2), (976, 1), (977, 5), (978, 1), (979, 3), (980, 3), (981, 1), (982, 1), (983, 1), (984, 1), (985, 1), (986, 2), (987, 1), (988, 1), (989, 1), (990, 1), (991, 1), (992, 9), (993, 1), (994, 1), (995, 1), (996, 1), (997, 1), (998, 1)], [(12, 1), (30, 2), (42, 3), (43, 3), (53, 1), (54, 1), (67, 1), (74, 1), (82, 1), (168, 1), (174, 1), (186, 2), (193, 1), (232, 1), (262, 2), (289, 1), (316, 1), (326, 1), (350, 1), (377, 1), (382, 1), (390, 1), (410, 1), (425, 1), (488, 1), (495, 2), (525, 1), (566, 1), (625, 1), (745, 2), (746, 1), (747, 2), (748, 3), (766, 1), (772, 1), (803, 1), (814, 2), (862, 2), (999, 1), (1000, 1), (1001, 1), (1002, 1), (1003, 1), (1004, 1), (1005, 1), (1006, 2), (1007, 1), (1008, 1), (1009, 1), (1010, 1), (1011, 1), (1012, 1), (1013, 1), (1014, 2), (1015, 1), (1016, 1), (1017, 1), (1018, 2), (1019, 1), (1020, 1)], [(4, 2), (5, 1), (12, 1), (22, 1), (30, 5), (36, 1), (38, 1), (42, 1), (43, 2), (58, 1), (79, 1), (83, 4), (91, 2), (97, 2), (124, 1), (181, 1), (289, 3), (298, 1), (311, 1), (373, 1), (390, 1), (428, 1), (459, 2), (463, 1), (495, 1), (516, 2), (552, 1), (745, 1), (748, 2), (809, 1), (818, 4), (820, 2), (825, 1), (874, 1), (895, 1), (919, 1), (933, 1), (996, 1), (998, 2), (1002, 1), (1011, 1), (1021, 2), (1022, 1), (1023, 2), (1024, 3), (1025, 1), (1026, 1), (1027, 1), (1028, 1), (1029, 1), (1030, 1), (1031, 1), (1032, 1), (1033, 1), (1034, 1), (1035, 1), (1036, 1), (1037, 3), (1038, 1), (1039, 2), (1040, 1), (1041, 1), (1042, 1), (1043, 1), (1044, 1), (1045, 1), (1046, 2), (1047, 1), (1048, 1), (1049, 1), (1050, 1), (1051, 1), (1052, 1), (1053, 1), (1054, 1), (1055, 2)], [(11, 1), (18, 1), (38, 1), (55, 1), (91, 1), (124, 2), (161, 1), (162, 1), (191, 2), (216, 1), (226, 2), (249, 1), (357, 2), (363, 1), (396, 4), (415, 1), (421, 1), (471, 1), (488, 2), (525, 1), (603, 1), (703, 1), (743, 1), (746, 1), (803, 1), (850, 1), (872, 12), (883, 1), (928, 1), (942, 1), (947, 1), (957, 4), (1004, 1), (1034, 1), (1056, 2), (1057, 1), (1058, 1), (1059, 1), (1060, 1), (1061, 1), (1062, 1), (1063, 1), (1064, 1), (1065, 1)], [(16, 1), (21, 1), (23, 1), (31, 1), (56, 2), (70, 1), (81, 1), (83, 6), (84, 4), (88, 1), (92, 1), (109, 3), (118, 18), (132, 3), (133, 1), (134, 1), (148, 1), (167, 1), (168, 1), (169, 2), (173, 13), (174, 1), (178, 1), (185, 3), (186, 2), (193, 1), (199, 1), (201, 1), (213, 11), (218, 1), (226, 1), (236, 1), (238, 3), (280, 1), (289, 1), (290, 2), (304, 2), (313, 1), (316, 1), (336, 1), (339, 1), (347, 1), (352, 2), (355, 1), (360, 2), (361, 1), (364, 1), (373, 1), (375, 2), (382, 1), (387, 1), (400, 1), (402, 1), (410, 1), (412, 2), (416, 1), (421, 1), (425, 1), (430, 1), (444, 1), (458, 1), (471, 2), (480, 2), (520, 1), (528, 2), (535, 1), (536, 1), (538, 1), (542, 1), (544, 5), (545, 1), (547, 2), (557, 1), (562, 2), (566, 2), (567, 1), (578, 1), (585, 2), (589, 7), (616, 1), (625, 1), (628, 2), (652, 1), (710, 1), (711, 1), (718, 1), (728, 2), (732, 1), (742, 1), (746, 1), (756, 1), (759, 1), (761, 6), (766, 1), (775, 5), (784, 1), (799, 1), (803, 1), (815, 1), (820, 1), (843, 1), (862, 1), (865, 1), (872, 1), (874, 3), (894, 1), (902, 1), (933, 1), (954, 1), (980, 1), (983, 5), (989, 4), (998, 1), (1009, 2), (1019, 1), (1025, 3), (1053, 1), (1066, 1), (1067, 1), (1068, 1), (1069, 2), (1070, 1), (1071, 1), (1072, 2), (1073, 1), (1074, 1), (1075, 1), (1076, 1), (1077, 1), (1078, 1), (1079, 2), (1080, 1), (1081, 3), (1082, 1), (1083, 1), (1084, 1), (1085, 1), (1086, 1), (1087, 1), (1088, 1), (1089, 1), (1090, 2), (1091, 3), (1092, 5), (1093, 1), (1094, 3), (1095, 1), (1096, 1), (1097, 2), (1098, 1), (1099, 1), (1100, 1), (1101, 1), (1102, 1), (1103, 3), (1104, 1), (1105, 1), (1106, 1), (1107, 2), (1108, 1), (1109, 1), (1110, 2), (1111, 1), (1112, 1), (1113, 1), (1114, 1), (1115, 1), (1116, 8), (1117, 1), (1118, 7), (1119, 1), (1120, 1), (1121, 2), (1122, 1), (1123, 1), (1124, 1), (1125, 1), (1126, 1), (1127, 1), (1128, 1)], [(12, 3), (18, 1), (29, 5), (31, 2), (36, 3), (42, 1), (43, 1), (45, 1), (52, 4), (53, 1), (61, 1), (70, 1), (83, 4), (90, 2), (109, 7), (110, 3), (134, 1), (149, 1), (162, 2), (177, 1), (180, 1), (188, 2), (193, 1), (211, 1), (214, 1), (216, 1), (231, 1), (238, 3), (247, 3), (271, 1), (291, 1), (325, 5), (335, 1), (372, 1), (373, 3), (384, 1), (399, 1), 

### Create an index to word dictionary

In [62]:
temp = dictionary[0]  # This is only to "load" the dictionary.
id2word = dictionary.id2token

### Train the Topic model

### What is LDA (Latent Dirichlet Allocation)?

**LDA** is a topic modeling algorithm that automatically discovers **topics** hidden in a collection of documents.


- Each **document** is made up of several **topics**.  
- Each **topic** is made up of certain **words** that often appear together.

Example:  
A document might be **70% "machine learning"** and **30% "healthcare"**,  
and the "machine learning" topic might include words like *model, data, algorithm*.


### How it works (in plain terms)

1. **Start with random guesses** of which topics belong to which words.  
2. For each word, update the topic assignment based on:
   - how common the topic is in the document  
   - how common the word is in that topic  
3. Repeat many times.  
4. Gradually, the model finds stable patterns where topics and words fit well.


**In short:**  
> LDA learns which words group together into topics  
> and how much of each topic is present in every document.

In [63]:
ldamodel = LdaModel(corpus, num_topics=15, id2word = id2word, passes=20)

### Display the topics

In [ ]:
pprint(ldamodel.top_topics(corpus,topn=5))

[([(np.float32(0.015720382), 'file'),
   (np.float32(0.011163963), 'http'),
   (np.float32(0.010989649), 'csv'),
   (np.float32(0.007671345), 'contains'),
   (np.float32(0.007087897), 'com')],
  np.float64(-0.9941452179024873)),
 ([(np.float32(0.03345198), 'text'),
   (np.float32(0.024020923), 'word'),
   (np.float32(0.020386241), 'language'),
   (np.float32(0.019431308), 'speech'),
   (np.float32(0.017333686), 'corpus')],
  np.float64(-1.3066421243029427)),
 ([(np.float32(0.031081242), 'model'),
   (np.float32(0.024423623), 'image'),
   (np.float32(0.019049956), 'trained'),
   (np.float32(0.0132447025), 'feature'),
   (np.float32(0.012674279), 'pre')],
  np.float64(-1.359354026943187)),
 ([(np.float32(0.026515888), 'restaurant'),
   (np.float32(0.024789527), 'year'),
   (np.float32(0.0193515), 'review'),
   (np.float32(0.016200973), 'city'),
   (np.float32(0.015434203), 'information')],
  np.float64(-1.428446937503389)),
 ([(np.float32(0.011719833), 'year'),
   (np.float32(0.008455161), 'state'),
   (np.float32(0.00830159), 'country'),
   (np.float32(0.007681999), 'information'),
   (np.float32(0.0068522673), 'health')],
  np.float64(-1.5799657527623765)),
 ([(np.float32(0.018605994), 'column'),
   (np.float32(0.012888295), 'crime'),
   (np.float32(0.012236292), 'number'),
   (np.float32(0.011104517), 'variable'),
   (np.float32(0.010848646), 'day')],
  np.float64(-1.914869302349602)),
 ([(np.float32(0.02789208), 'city'),
   (np.float32(0.018216101), 'new'),
   (np.float32(0.01740116), 'csv'),
   (np.float32(0.015192417), 'york'),
   (np.float32(0.014345282), 'property')],
  np.float64(-2.033335985029097)),
 ([(np.float32(0.42850363), 'university'),
   (np.float32(0.08042766), 'state'),
   (np.float32(0.053604305), 'college'),
   (np.float32(0.02364492), 'california'),
   (np.float32(0.022005655), 'texas')],
  np.float64(-2.51880602100133)),
 ([(np.float32(0.034573775), 'time'),
   (np.float32(0.021644147), 'attack'),
   (np.float32(0.019166917), 'formula'),
   (np.float32(0.017138278), 'feature'),
   (np.float32(0.015571362), 'score')],
  np.float64(-2.672142529147287)),
 ([(np.float32(0.032120023), 'de'),
   (np.float32(0.026657606), 'team'),
   (np.float32(0.023122748), 'question'),
   (np.float32(0.017831927), 'player'),
   (np.float32(0.016932793), 'vote')],
  np.float64(-2.8177920044086884)),
 ([(np.float32(0.046516195), 'csv'),
   (np.float32(0.040997043), 'row'),
   (np.float32(0.024386464), 'facility'),
   (np.float32(0.018032717), 'student'),
   (np.float32(0.015845818), 'education')],
  np.float64(-2.967552256401963)),
 ([(np.float32(0.034979355), 'tweet'),
   (np.float32(0.033673365), 'game'),
   (np.float32(0.030671496), 'player'),
   (np.float32(0.026407), 'time'),
   (np.float32(0.019439466), 'many')],
  np.float64(-3.723640541422102)),
 ([(np.float32(0.055926394), 'description'),
   (np.float32(0.046363927), 'yet'),
   (np.float32(0.023234123), 'instance'),
   (np.float32(0.023085997), 'cell'),
   (np.float32(0.021980092), 'price')],
  np.float64(-5.047269152953379)),
 ([(np.float32(0.02560314), 'word'),
   (np.float32(0.020918969), 'product'),
   (np.float32(0.019016461), 'different'),
   (np.float32(0.018668959), 'sale'),
   (np.float32(0.01671897), 'car')],
  np.float64(-5.062579404462412)),
 ([(np.float32(0.02185492), 'weapon'),
   (np.float32(0.0180488), 'back'),
   (np.float32(0.015471333), 'customer'),
   (np.float32(0.015018036), 'solar'),
   (np.float32(0.0149346795), 'center')],
  np.float64(-14.9755843032159))]

### Display the 15 topics with words

In [ ]:
for idx in range(15):
    print("Topic #%s:" % idx, ldamodel.print_topic(idx, 10))

Topic #0: 0.019*"column" + 0.013*"crime" + 0.012*"number" + 0.011*"variable" + 0.011*"day" + 0.011*"activity" + 0.011*"per" + 0.010*"value" + 0.009*"weather" + 0.009*"year"
Topic #1: 0.032*"de" + 0.027*"team" + 0.023*"question" + 0.018*"player" + 0.017*"vote" + 0.016*"news" + 0.013*"percentage" + 0.013*"la" + 0.013*"point" + 0.012*"per"
Topic #2: 0.429*"university" + 0.080*"state" + 0.054*"college" + 0.024*"california" + 0.022*"texas" + 0.017*"institute" + 0.013*"north" + 0.012*"new" + 0.011*"florida" + 0.011*"technology"
Topic #3: 0.047*"csv" + 0.041*"row" + 0.024*"facility" + 0.018*"student" + 0.016*"education" + 0.016*"gas" + 0.015*"california" + 0.015*"url" + 0.014*"lat" + 0.014*"column"
Topic #4: 0.031*"model" + 0.024*"image" + 0.019*"trained" + 0.013*"feature" + 0.013*"pre" + 0.011*"learning" + 0.010*"recognition" + 0.010*"research" + 0.009*"contains" + 0.009*"network"
Topic #5: 0.022*"weapon" + 0.018*"back" + 0.015*"customer" + 0.015*"solar" + 0.015*"center" + 0.014*"service" + 0.014*"time" + 0.013*"district" + 0.012*"may" + 0.012*"lower"
Topic #6: 0.056*"description" + 0.046*"yet" + 0.023*"instance" + 0.023*"cell" + 0.022*"price" + 0.021*"company" + 0.012*"time" + 0.012*"group" + 0.009*"attribute" + 0.009*"number"
Topic #7: 0.027*"restaurant" + 0.025*"year" + 0.019*"review" + 0.016*"city" + 0.015*"information" + 0.013*"survey" + 0.013*"null" + 0.011*"non" + 0.011*"table" + 0.011*"investment"
Topic #8: 0.028*"city" + 0.018*"new" + 0.017*"csv" + 0.015*"york" + 0.014*"property" + 0.013*"name" + 0.012*"dog" + 0.012*"http" + 0.011*"government" + 0.011*"federal"
Topic #9: 0.012*"year" + 0.008*"state" + 0.008*"country" + 0.008*"information" + 0.007*"health" + 0.006*"world" + 0.006*"report" + 0.006*"survey" + 0.005*"research" + 0.005*"time"
Topic #10: 0.035*"tweet" + 0.034*"game" + 0.031*"player" + 0.026*"time" + 0.019*"many" + 0.019*"match" + 0.017*"season" + 0.014*"user" + 0.013*"twitter" + 0.013*"team"
Topic #11: 0.033*"text" + 0.024*"word" + 0.020*"language" + 0.019*"speech" + 0.017*"corpus" + 0.015*"song" + 0.015*"integer" + 0.013*"name" + 0.012*"file" + 0.011*"txt"
Topic #12: 0.016*"file" + 0.011*"http" + 0.011*"csv" + 0.008*"contains" + 0.007*"com" + 0.007*"one" + 0.007*"id" + 0.007*"number" + 0.006*"information" + 0.006*"use"
Topic #13: 0.035*"time" + 0.022*"attack" + 0.019*"formula" + 0.017*"feature" + 0.016*"score" + 0.015*"genre" + 0.014*"max" + 0.014*"competition" + 0.014*"audio" + 0.013*"mile"
Topic #14: 0.026*"word" + 0.021*"product" + 0.019*"different" + 0.019*"sale" + 0.017*"car" + 0.014*"used" + 0.013*"inspiration" + 0.012*"information" + 0.011*"language" + 0.011*"contains"

## LSI Model

**LSI**, also called **LSA (Latent Semantic Analysis)**, is a method that finds **hidden relationships between words and documents** by using **math (linear algebra)** instead of probabilities.

- Each **document** can be represented as a vector of words.  
- Some words mean similar things and often appear together.  
- LSI reduces the data to a smaller set of **concepts (topics)** that capture those hidden patterns.


### How it works

1. Build a **document–term matrix** (counts of each word in each document).  
2. Apply **Singular Value Decomposition (SVD)**, a mathematical technique that breaks the matrix into three smaller matrices:
   - documents × concepts  
   - concepts × words  
3. Keep only the top *k* concepts (topics).  
4. These concepts represent the main themes in the data.


**In short:**  
> LSI uses math (SVD) to uncover hidden themes,  
> showing which documents and words are related through shared meaning —  
> not just exact word matches.

In [64]:
from gensim.models import LsiModel
lsamodel = LsiModel(corpus, num_topics=10, id2word = id2word)
pprint(lsamodel.print_topics(num_topics=10, num_words=10))

[(0,
  '0.970*"developer" + 0.174*"convicted" + 0.076*"week" + 0.051*"simply" + '
  '0.049*"txt" + 0.039*"four" + 0.031*"formation" + 0.028*"damage" + '
  '0.027*"unesco" + 0.027*"become"'),
 (1,
  '0.389*"holy" + 0.248*"match" + 0.221*"station" + 0.200*"accessible" + '
  '0.177*"obtained" + 0.173*"ultimate" + 0.159*"financial" + 0.156*"except" + '
  '0.147*"constantly" + 0.126*"affiliated"'),
 (2,
  '0.436*"holy" + 0.307*"station" + 0.259*"match" + -0.250*"extracting" + '
  '-0.225*"serve" + 0.175*"affiliated" + 0.173*"constantly" + '
  '-0.154*"ultimate" + 0.151*"michael" + -0.133*"except"'),
 (3,
  '0.595*"extracting" + 0.535*"serve" + 0.263*"different" + 0.261*"drop" + '
  '0.119*"complicated" + 0.116*"holy" + -0.098*"ultimate" + -0.093*"financial" '
  '+ 0.090*"station" + -0.088*"except"'),
 (4,
  '-0.402*"financial" + 0.325*"without" + 0.266*"max" + 0.198*"url" + '
  '0.192*"worst" + 0.186*"interest" + 0.180*"cleaning" + 0.174*"found" + '
  '0.170*"goal" + 0.165*"quantity"'),
 (5,
  '0.535*"except" + -0.436*"financial" + -0.193*"accessible" + '
  '0.174*"ultimate" + -0.166*"without" + -0.155*"senior" + -0.122*"max" + '
  '-0.120*"converted" + 0.104*"required" + 0.103*"attempt"'),
 (6,
  '-0.680*"required" + 0.470*"except" + -0.431*"attempt" + -0.104*"choice" + '
  '0.096*"financial" + 0.063*"ultimate" + -0.063*"remedy" + -0.060*"structure" '
  '+ -0.058*"range" + -0.053*"null"'),
 (7,
  '-0.552*"except" + -0.487*"required" + -0.282*"financial" + -0.198*"attempt" '
  '+ 0.139*"hot" + 0.125*"dal" + 0.113*"trade" + 0.098*"choice" + '
  '-0.095*"senior" + 0.088*"totaling"'),
 (8,
  '-0.364*"classification" + 0.246*"financial" + -0.234*"pozzolo" + '
  '-0.221*"public" + 0.203*"hot" + -0.184*"briggs" + -0.175*"costing" + '
  '-0.167*"accessible" + -0.166*"nursing" + 0.154*"senior"'),
 (9,
  '-0.409*"classification" + -0.266*"briggs" + -0.251*"nursing" + '
  '-0.236*"unbalanced" + -0.216*"dal" + -0.204*"costing" + 0.196*"pozzolo" + '
  '0.187*"public" + 0.185*"named" + -0.158*"dancing"')]

In [65]:
for idx in range(10):
    print("Topic #%s:" % idx, lsamodel.print_topic(idx, 10))
print("=" * 20)

Topic #0: 0.970*"developer" + 0.174*"convicted" + 0.076*"week" + 0.051*"simply" + 0.049*"txt" + 0.039*"four" + 0.031*"formation" + 0.028*"damage" + 0.027*"unesco" + 0.027*"become"
Topic #1: 0.389*"holy" + 0.248*"match" + 0.221*"station" + 0.200*"accessible" + 0.177*"obtained" + 0.173*"ultimate" + 0.159*"financial" + 0.156*"except" + 0.147*"constantly" + 0.126*"affiliated"
Topic #2: 0.436*"holy" + 0.307*"station" + 0.259*"match" + -0.250*"extracting" + -0.225*"serve" + 0.175*"affiliated" + 0.173*"constantly" + -0.154*"ultimate" + 0.151*"michael" + -0.133*"except"
Topic #3: 0.595*"extracting" + 0.535*"serve" + 0.263*"different" + 0.261*"drop" + 0.119*"complicated" + 0.116*"holy" + -0.098*"ultimate" + -0.093*"financial" + 0.090*"station" + -0.088*"except"
Topic #4: -0.402*"financial" + 0.325*"without" + 0.266*"max" + 0.198*"url" + 0.192*"worst" + 0.186*"interest" + 0.180*"cleaning" + 0.174*"found" + 0.170*"goal" + 0.165*"quantity"
Topic #5: 0.535*"except" + -0.436*"financial" + -0.193*"accessible" + 0.174*"ultimate" + -0.166*"without" + -0.155*"senior" + -0.122*"max" + -0.120*"converted" + 0.104*"required" + 0.103*"attempt"
Topic #6: -0.680*"required" + 0.470*"except" + -0.431*"attempt" + -0.104*"choice" + 0.096*"financial" + 0.063*"ultimate" + -0.063*"remedy" + -0.060*"structure" + -0.058*"range" + -0.053*"null"
Topic #7: -0.552*"except" + -0.487*"required" + -0.282*"financial" + -0.198*"attempt" + 0.139*"hot" + 0.125*"dal" + 0.113*"trade" + 0.098*"choice" + -0.095*"senior" + 0.088*"totaling"
Topic #8: -0.364*"classification" + 0.246*"financial" + -0.234*"pozzolo" + -0.221*"public" + 0.203*"hot" + -0.184*"briggs" + -0.175*"costing" + -0.167*"accessible" + -0.166*"nursing" + 0.154*"senior"
Topic #9: -0.409*"classification" + -0.266*"briggs" + -0.251*"nursing" + -0.236*"unbalanced" + -0.216*"dal" + -0.204*"costing" + 0.196*"pozzolo" + 0.187*"public" + 0.185*"named" + -0.158*"dancing"
====================

## Visualize the topics and documents with the trained Topic Model
- Use pyLDAvis from gensim

In [66]:
%%capture
!pip install pyLDAvis

In [67]:
import pyLDAvis.gensim

### Enable the notebook for visualization

In [68]:
import warnings
warnings.filterwarnings("ignore")

In [69]:
pyLDAvis.enable_notebook()

### Visualize the Topic model

### What is λ (Lambda) in pyLDAvis?

The **λ slider** controls how the most relevant words for each topic are chosen.

- **λ = 1.0** → shows the most **frequent** words in that topic.  
- **λ = 0.0** → shows the most **unique or exclusive** words to that topic.  
- **λ ≈ 0.6 (default)** → balances between frequency and uniqueness.

Move λ **left** to see what makes the topic special,  
move it **right** to see the most common words within the topic.

In [70]:
pyLDAvis.gensim.prepare(ldamodel, corpus, dictionary)

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
8      0.235090  0.000004       1        1  39.380036
12     0.210936 -0.102763       2        1  31.058057
14     0.118116 -0.000947       3        1   4.046986
1     -0.021783  0.081242       4        1   3.865594
2      0.125391 -0.033181       5        1   3.836327
13     0.047435 -0.062198       6        1   3.396939
0     -0.046721  0.109987       7        1   2.639369
10    -0.005162 -0.022965       8        1   2.473465
7      0.042351  0.010370       9        1   2.089896
11     0.025522  0.042848      10        1   1.525927
9     -0.026405  0.064180      11        1   1.425215
4     -0.140042  0.065532      12        1   1.142425
3     -0.232578 -0.299606      13        1   1.120850
6     -0.158223  0.063634      14        1   1.102839
5     -0.173928  0.083863      15        1   0.896073, topic_info=                Term         Freq        Total Category  logprob  loglift
579        developer   894.000000   894.000000  Default  30.0000  30.0000
566        convicted   826.000000   826.000000  Default  29.0000  29.0000
200             holy   532.000000   532.000000  Default  28.0000  28.0000
603           except  1018.000000  1018.000000  Default  27.0000  27.0000
772        worldwide   596.000000   596.000000  Default  26.0000  26.0000
...              ...          ...          ...      ...      ...      ...
1428  characteristic    13.118442   205.078469  Topic15  -5.0359   1.9655
761            usage    12.877113   240.853262  Topic15  -5.0544   1.7862
347          costing    11.431038   395.112602  Topic15  -5.1735   1.1721
180              far    10.837400   451.281734  Topic15  -5.2269   0.9858
516       accessible     7.904633  1224.290778  Topic15  -5.5424  -0.3278

[899 rows x 6 columns], token_table=      Topic      Freq     Term
term
1549      1  0.213979  absence
1549      3  0.454705  absence
1549      5  0.227353  absence
1549      9  0.066868  absence
1549     11  0.026747  absence
...     ...       ...      ...
515       9  0.162191     zero
515      11  0.007912     zero
515      14  0.027691     zero
2057      1  0.192777   zillow
2057      4  0.819303   zillow

[2161 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[9, 13, 15, 2, 3, 14, 1, 11, 8, 12, 10, 5, 4, 7, 6])