In [38]:
import nltk
import numpy as np
import random
import string

from bs4 import BeautifulSoup
import urllib.request
import re

### Grab articles from wikipedia

In [39]:
# Define URL and headers (pretend to be a real browser)
url = "https://en.wikipedia.org/wiki/Natural_language_processing"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

# Create a request object with headers
req = urllib.request.Request(url, headers=headers)

# Open and read the page
with urllib.request.urlopen(req) as response:
    raw_html = response.read()

# Parse the HTML using BeautifulSoup
article_html = BeautifulSoup(raw_html, "lxml")

# Extract all paragraph tags
article_paragraphs = article_html.find_all("p")

# Combine all text into one string
article_text = ""
for para in article_paragraphs:
    article_text += para.get_text()

# Display first few hundred characters for verification
print(article_text[:500])

Natural language processing (NLP) is the processing of natural language information by a computer. NLP is a subfield of computer science and is closely associated with artificial intelligence. NLP is also related to information retrieval, knowledge representation, computational linguistics, and linguistics more broadly.[1]
Major processing tasks in an NLP system include: speech recognition, text classification, natural language understanding, and natural language generation.
Natural language pr

In [3]:
raw_html

b'<!DOCTYPE html>\n<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard" lang="en" dir="ltr">\n<head>\n<meta charset="UTF-8">\n<title>Natural language processing - Wikipedia</title>\n<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split(\'%2C\').forEach(function(pref){className=className.replace(new RegExp(\'(^| )\'+pref.replace(/-clientpref-\\w+$|[^\\w-]+/g,\'\')+\'-clientpref-\\\\w+( |$)\'),\'$1\'+pref+\'$2\');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"48fc7f56-f74b-482e-880f-ad5900f8f872","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Natural_language_processing","wgTitle":"Natural language processing","wgCurRevisionId":1340459730,"wgRevisionId":1340459730,"wgArticleId":21652,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["All accuracy disputes","Accuracy disputes from December 2013","Harv and Sfn no-target errors","CS1 errors: periodical ignored","CS1 maint: work parameter with ISBN","CS1 maint: location","Articles with short description","Short description is different from Wikidata","Articles needing additional references from May 2024","All articles needing additional references","Wikipedia articles needing rewrite from July 2025","All articles needing rewrite","Wikipedia articles needing reorganization from July 2025","Articles with multiple maintenance issues","Commons category link from Wikidata","Natural language processing","Computational fields of study","Computational linguistics","Speech recognition"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Natural_language_processing","wgRelevantArticleId":21652,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":60000,"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q30642","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgGEUseTestKitchenExtension":true,"wgMetricsPlatformUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]},"wgTestKitchenUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]}};\nRLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","ext.math.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready","ext.wp25EasterEggs.styles":"ready"};RLPAGEMODULES=["ext.parsermigration.survey","ext.cite.ux-enhancements","ext.math.polyfills","mediawiki.page.media","ext.scribunto.logs","site","mediawiki.page.ready","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession","ext.xLab","ext.testKitchen","ext.wp25EasterEggs"];</script>\n<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\\\","watchToken":"+\\\\","csrfToken":"+\\\\"});\n}];});});</script>\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.math.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediamessages.styles%7Cext.wp25EasterEggs.styles%7Cjquery.makeCollapsible.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022">\n<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>\n<meta name="ResourceLoaderDynamicStyles" content="">\n<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022">\n<meta name="generator" content="MediaWiki 1.46.0-wmf.17">\n<meta name="referrer" content="origin">\n<meta name="referrer" content="origin-when-cross-origin">\n<meta name="robots" content="max-image-preview:standard">\n<meta name="format-detection" content="telephone=no">\n<meta name="viewport" content="width=1120">\n<meta property="og:title" content="Natural language processing - Wikipedia">\n<meta property="og:type" content="website">\n<link rel="preconnect" href="//upload.wikimedia.org">\n<link rel="alternate" type="application/x-wiki" title="Edit this page" href="/w/index.php?title=Natural_language_processing&amp;action=edit">\n<link rel="apple-touch-icon" href="/static/apple-touch/wikipedia.png">\n<link rel="icon" href="/static/favicon/wikipedia.ico">\n<link rel="search" type="application/opensearchdescription+xml" href="/w/rest.php/v1/search" title="Wikipedia (en)">\n<link rel="EditURI" type="application/rsd+xml" href="//en.wikipedia.org/w/api.php?action=rsd">\n<link rel="canonical" href="https://en.wikipedia.org/wiki/Natural_language_processing">\n<link rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">\n<link rel="alternate" type="application/atom+xml" title="Wikipedia Atom feed" href="/w/index.php?title=Special:RecentChanges&amp;feed=atom">\n<link rel="dns-prefetch" href="//meta.wikimedia.org" />\n<link rel="dns-prefetch" href="auth.wikimedia.org">\n</head>\n<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-Natural_language_processing rootpage-Natural_language_processing skin-vector-2022 action-view">\n<div id="mw-aria-live-region" class="mw-aria-live-region" aria-live="polite"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>\n<div class="vector-header-container">\n\t<header class="vector-header mw-header no-font-mode-scale">\n\t\t<div class="vector-header-start">\n\t\t\t<nav class="vector-main-menu-landmark" aria-label="Site">\n\t\t\t\t\n<div id="vector-main-menu-dropdown" class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right"  title="Main menu" >\n\t<input type="checkbox" id="vector-main-menu-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-main-menu-dropdown" class="vector-dropdown-checkbox "  aria-label="Main menu"  >\n\t<label id="vector-main-menu-dropdown-label" for="vector-main-menu-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>\n\n<span class="vector-dropdown-label-text">Main menu</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\t\t<div id="vector-main-menu-unpinned-container" class="vector-unpinned-container">\n\t\t\n<div id="vector-main-menu" class="vector-main-menu vector-pinnable-element">\n\t<div\n\tclass="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned"\n\tdata-feature-name="main-menu-pinned"\n\tdata-pinnable-element-id="vector-main-menu"\n\tdata-pinned-container-id="vector-main-menu-pinned-container"\n\tdata-unpinned-container-id="vector-main-menu-unpinned-container"\n>\n\t<div class="vector-pinnable-header-label">Main menu</div>\n\t<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>\n\t<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>\n</div>\n\n\t\n<div id="p-navigation" class="vector-menu mw-portlet mw-portlet-navigation"  >\n\t<div class="vector-menu-heading">\n\t\tNavigation\n\t</div>\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="n-mainpage-description" class="mw-list-item"><a href="/wiki/Main_Page" title="Visit the main page [z]" accesskey="z"><span>Main page</span></a></li><li id="n-contents" class="mw-list-item"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li id="n-currentevents" class="mw-list-item"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li id="n-randompage" class="mw-list-item"><a href="/wiki/Special:Random" title="Visit a randomly selected article [x]" accesskey="x"><span>Random article</span></a></li><li id="n-aboutsite" class="mw-list-item"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li id="n-contactpage" class="mw-list-item"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-interaction" class="vector-menu mw-portlet mw-portlet-interaction"  >\n\t<div class="vector-menu-heading">\n\t\tContribute\n\t</div>\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t<li id="n-help" class="mw-list-item"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li id="n-introduction" class="mw-list-item"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li id="n-portal" class="mw-list-item"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li id="n-recentchanges" class="mw-list-item"><a href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]" accesskey="r"><span>Recent changes</span></a></li><li id="n-upload" class="mw-list-item"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li id="n-specialpages" class="mw-list-item"><a href="/wiki/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q"><span>Special pages</span></a></li>\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n</div>\n\n\t\t\t\t</div>\n\n\t</div>\n</div>\n\n\t\t</nav>\n\t\t\t\n<a href="/wiki/Main_Page" class="mw-logo">\n\t<img class="mw-logo-icon" src="/static/images/icons/enwiki-25.svg" alt="" aria-hidden="true" height="50" width="50">\n\t<span class="mw-logo-container skin-invert">\n\t\t<img class="mw-logo-wordmark" alt="Wikipedia" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;">\n\t\t<img class="mw-logo-tagline" alt="The Free Encyclopedia" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" width="140" height="11" style="width: 8.75em; height: 0.6875em;">\n\t</span>\n</a>\n\n\t\t</div>\n\t\t<div class="vector-header-end">\n\t\t\t\n<div id="p-search" role="search" class="vector-search-box-vue  vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box">\n\t<a href="/wiki/Special:Search" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" title="Search Wikipedia [f]" accesskey="f"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>\n\n<span>Search</span>\n\t</a>\n\t<div class="vector-typeahead-search-container">\n\t\t<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">\n\t\t\t<form action="/w/index.php" id="searchform" class="cdx-search-input cdx-search-input--has-end-button">\n\t\t\t\t<div id="simpleSearch" class="cdx-search-input__input-wrapper"  data-search-loc="header-moved">\n\t\t\t\t\t<div class="cdx-text-input cdx-text-input--has-start-icon">\n\t\t\t\t\t\t<input\n\t\t\t\t\t\t\tclass="cdx-text-input__input mw-searchInput" autocomplete="off"\n\t\t\t\t\t\t\t type="search" name="search" placeholder="Search Wikipedia" aria-label="Search Wikipedia" autocapitalize="none" spellcheck="false" title="Search Wikipedia [f]" accesskey="f" id="searchInput"\n\t\t\t\t\t\t\t>\n\t\t\t\t\t\t<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>\n\t\t\t\t\t</div>\n\t\t\t\t\t<input type="hidden" name="title" value="Special:Search">\n\t\t\t\t</div>\n\t\t\t\t<button class="cdx-button cdx-search-input__end-button">Search</button>\n\t\t\t</form>\n\t\t</div>\n\t</div>\n</div>\n\n\t\t\t<nav class="vector-user-links vector-user-links-wide" aria-label="Personal tools">\n\t<div class="vector-user-links-main">\n\t\n<div id="p-vector-user-menu-preferences" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-vector-user-menu-userpage" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t<nav class="vector-appearance-landmark" aria-label="Appearance">\n\t\t\n<div id="vector-appearance-dropdown" class="vector-dropdown "  title="Change the appearance of the page&#039;s font size, width, and color" >\n\t<input type="checkbox" id="vector-appearance-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-appearance-dropdown" class="vector-dropdown-checkbox "  aria-label="Appearance"  >\n\t<label id="vector-appearance-dropdown-label" for="vector-appearance-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>\n\n<span class="vector-dropdown-label-text">Appearance</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\t<div id="vector-appearance-unpinned-container" class="vector-unpinned-container">\n\t\t\t\t\n\t\t\t</div>\n\t\t\n\t</div>\n</div>\n\n\t</nav>\n\t\n<div id="p-vector-user-menu-notifications" class="vector-menu mw-portlet emptyPortlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t\n<div id="p-vector-user-menu-overflow" class="vector-menu mw-portlet"  >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t<li id="pt-sitesupport-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw-interface  href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en" class=""><span>Donate</span></a>\n</li>\n<li id="pt-createaccount-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw-interface  href="/w/index.php?title=Special:CreateAccount&amp;returnto=Natural+language+processing" title="You are encouraged to create an account and log in; however, it is not mandatory" class=""><span>Create account</span></a>\n</li>\n<li id="pt-login-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw-interface  href="/w/index.php?title=Special:UserLogin&amp;returnto=Natural+language+processing" title="You&#039;re encouraged to log in; however, it&#039;s not mandatory. [o]" accesskey="o" class=""><span>Log in</span></a>\n</li>\n\n\t\t\t\n\t\t</ul>\n\t\t\n\t</div>\n</div>\n\n\t</div>\n\t\n<div id="vector-user-links-dropdown" class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out user-links-collapsible-item"  title="Log in and more options" >\n\t<input type="checkbox" id="vector-user-links-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-user-links-dropdown" class="vector-dropdown-checkbox "  aria-label="Personal tools"  >\n\t<label id="vector-user-links-dropdown-label" for="vector-user-links-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>\n\n<span class="vector-dropdown-label-text">Personal tools</span>\n\t</label>\n\t<div class="vector-dropdown-content">\n\n\n\t\t\n<div id="p-personal" class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item"  title="User menu" >\n\t<div class="vector-menu-content">\n\t\t\n\t\t<ul class="vector-menu-content-list">\n\t\t\t\n\t\

In [4]:
article_html

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>Natural language processing - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"48fc7f56-f74b-482e-880f-ad5900f8f872","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Natural_language_processing","wgTitle":"Natural language processing","wgCurRevisionId":1340459730,"wgRevisionId":1340459730,"wgArticleId":21652,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["All accuracy disputes","Accuracy disputes from December 2013","Harv and Sfn no-target errors","CS1 errors: periodical ignored","CS1 maint: work parameter with ISBN","CS1 maint: location","Articles with short description","Short description is different from Wikidata","Articles needing additional references from May 2024","All articles needing additional references","Wikipedia articles needing rewrite from July 2025","All articles needing rewrite","Wikipedia articles needing reorganization from July 2025","Articles with multiple maintenance issues","Commons category link from Wikidata","Natural language processing","Computational fields of study","Computational linguistics","Speech recognition"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Natural_language_processing","wgRelevantArticleId":21652,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":60000,"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q30642","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgGEUseTestKitchenExtension":true,"wgMetricsPlatformUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]},"wgTestKitchenUserExperiments":{"active_experiments":[],"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[],"sampling_units":[],"coordinator":[]}};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","ext.math.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready","ext.wp25EasterEggs.styles":"ready"};RLPAGEMODULES=["ext.parsermigration.survey","ext.cite.ux-enhancements","ext.math.polyfills","mediawiki.page.media","ext.scribunto.logs","site","mediawiki.page.ready","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession","ext.xLab","ext.testKitchen","ext.wp25EasterEggs"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.math.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediamessages.styles%7Cext.wp25EasterEggs.styles%7Cjquery.makeCollapsible.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.46.0-wmf.17" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="width=1120" name="viewport"/>
<meta content="Natural language processing - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="/w/index.php?title=Natural_language_processing&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/Natural_language_processing" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch"/>
<link href="auth.wikimedia.org" rel="dns-prefetch"/>
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-Natural_language_processing rootpage-Natural_language_processing skin-vector-2022 action-view">
<div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header no-font-mode-scale">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=Natural+language+processing" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=Natural+language+processing" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out user-links-collapsible-item" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">

In [5]:
article_text

'\nNatural language processing (NLP) is the processing of natural language information by a computer. NLP is a subfield of computer science and is closely associated with artificial intelligence. NLP is also related to information retrieval, knowledge representation, computational linguistics, and linguistics more broadly.[1]\nMajor processing tasks in an NLP system include: speech recognition, text classification, natural language understanding, and natural language generation.\nNatural language processing has its roots in the 1950s.[2] Already in 1950, Alan Turing published an article titled "Computing Machinery and Intelligence" which proposed what is now called the Turing test as a criterion of intelligence, though at the time that was not articulated as a problem separate from artificial intelligence. The proposed test includes a task that involves the automated interpretation and generation of natural language.\nThe premise of symbolic NLP is often illustrated using John Searle\'s Chinese room thought experiment: Given a collection of rules (e.g., a Chinese phrasebook, with questions and matching answers), the computer emulates natural language understanding (or other NLP tasks) by applying those rules to the data it confronts.\nUp until the 1980s, most natural language processing systems were based on complex sets of hand-written rules. Starting in the late 1980s, however, there was a revolution in natural language processing with the introduction of machine learning algorithms for language processing. This shift was influenced by increasing computational power (see Moore\'s law) and a decline in the dominance of Chomskyan linguistic theories... (e.g. transformational grammar), whose theoretical underpinnings discouraged the sort of corpus linguistics that underlies the machine-learning approach to language processing.[9]\nSymbolic approach, i.e., the hand-coding of a set of rules for manipulating symbols, coupled with a dictionary lookup, was historically the first approach used both by AI in general and by NLP in particular:[19][20] such as by writing grammars or devising heuristic rules for stemming.\nMachine learning approaches, which include both statistical and neural networks, on the other hand, have many advantages over the symbolic approach:\nRule-based systems are commonly used:\nIn the late 1980s and mid-1990s, the statistical approach ended a period of AI winter, which was caused by the inefficiencies of the rule-based approaches.[21][22]\nThe earliest decision trees, producing systems of hard if–then rules, were still very similar to the old rule-based approaches.\nOnly the introduction of hidden Markov models, applied to part-of-speech tagging, announced the end of the old rule-based approach.\nA major drawback of statistical methods is that they require elaborate feature engineering. Since 2015,[23] neural network–based methods have increasingly replaced traditional statistical approaches, using semantic networks[24] and word embeddings to capture semantic properties of words.\nIntermediate tasks (e.g., part-of-speech tagging and dependency parsing) are not needed anymore.\nNeural machine translation, based on then-newly invented sequence-to-sequence transformations, made obsolete the intermediate steps, such as word alignment, previously necessary for statistical machine translation.\nThe following is a list of some of the most commonly researched tasks in natural language processing. Some of these tasks have direct real-world applications, while others more commonly serve as subtasks that are used to aid in solving larger tasks.\nThough natural language processing tasks are closely intertwined, they can be subdivided into categories for convenience. A coarse division is given below.\nBased on long-standing trends in the field, it is possible to extrapolate future directions of NLP. As of 2020, three trends among the topics of the long-standing series of CoNLL Shared Tasks can be observed:[49]\nMost higher-level NLP applications involve aspects that emulate intelligent behavior and apparent comprehension of natural language. More broadly speaking, the technical operationalization of increasingly advanced aspects of cognitive behavior represents one of the developmental trajectories of NLP (see trends among CoNLL shared tasks above).\nCognition refers to "the mental action or process of acquiring knowledge and understanding through thought, experience, and the senses."[50] Cognitive science is the interdisciplinary, scientific study of the mind and its processes.[51] Cognitive linguistics is an interdisciplinary branch of linguistics, combining knowledge and research from both psychology and linguistics.[52] Especially during the age of symbolic NLP, the area of computational linguistics maintained strong ties with cognitive studies.\nAs an example, George Lakoff offers a methodology to build natural language processing (NLP) algorithms through the perspective of cognitive science, along with the findings of cognitive linguistics,[53] with two defining aspects:\nTies with cognitive linguistics are part of the historical heritage of NLP, but they have been less frequently addressed since the statistical turn during the 1990s. Nevertheless, approaches to develop cognitive models towards technically operationalizable frameworks have been pursued in the context of various frameworks, e.g., of cognitive grammar,[56] functional grammar,[57] construction grammar,[58] computational psycholinguistics and cognitive neuroscience (e.g., ACT-R), however, with limited uptake in mainstream NLP (as measured by presence on major conferences[59] of the ACL). More recently, ideas of cognitive NLP have been revived as an approach to achieve explainability, e.g., under the notion of "cognitive AI".[60] Likewise, ideas of cognitive NLP are inherent to neural models multimodal NLP (although rarely made explicit)[61] and developments in artificial intelligence, specifically tools and technologies using large language model approaches[62] and new directions in artificial general intelligence based on the free energy principle[63] by British neuroscientist and theoretician at University College London Karl J. Friston.\n'

### Step 1: Tokenize

In [6]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /Users/user/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /Users/user/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/user/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/user/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [7]:
# Use a sentence tokenizer
corpus = nltk.sent_tokenize(article_text)

In [8]:
corpus

['\nNatural language processing (NLP) is the processing of natural language information by a computer.',
 'NLP is a subfield of computer science and is closely associated with artificial intelligence.',
 'NLP is also related to information retrieval, knowledge representation, computational linguistics, and linguistics more broadly.',
 '[1]\nMajor processing tasks in an NLP system include: speech recognition, text classification, natural language understanding, and natural language generation.',
 'Natural language processing has its roots in the 1950s.',
 '[2] Already in 1950, Alan Turing published an article titled "Computing Machinery and Intelligence" which proposed what is now called the Turing test as a criterion of intelligence, though at the time that was not articulated as a problem separate from artificial intelligence.',
 'The proposed test includes a task that involves the automated interpretation and generation of natural language.',
 "The premise of symbolic NLP is often illustrated using John Searle's Chinese room thought experiment: Given a collection of rules (e.g., a Chinese phrasebook, with questions and matching answers), the computer emulates natural language understanding (or other NLP tasks) by applying those rules to the data it confronts.",
 'Up until the 1980s, most natural language processing systems were based on complex sets of hand-written rules.',
 'Starting in the late 1980s, however, there was a revolution in natural language processing with the introduction of machine learning algorithms for language processing.',
 "This shift was influenced by increasing computational power (see Moore's law) and a decline in the dominance of Chomskyan linguistic theories... (e.g.",
 'transformational grammar), whose theoretical underpinnings discouraged the sort of corpus linguistics that underlies the machine-learning approach to language processing.',
 '[9]\nSymbolic approach, i.e., the hand-coding of a set of rules for manipulating symbols, coupled with a dictionary lookup, was historically the first approach used both by AI in general and by NLP in particular:[19][20] such as by writing grammars or devising heuristic rules for stemming.',
 'Machine learning approaches, which include both statistical and neural networks, on the other hand, have many advantages over the symbolic approach:\nRule-based systems are commonly used:\nIn the late 1980s and mid-1990s, the statistical approach ended a period of AI winter, which was caused by the inefficiencies of the rule-based approaches.',
 '[21][22]\nThe earliest decision trees, producing systems of hard if–then rules, were still very similar to the old rule-based approaches.',
 'Only the introduction of hidden Markov models, applied to part-of-speech tagging, announced the end of the old rule-based approach.',
 'A major drawback of statistical methods is that they require elaborate feature engineering.',
 'Since 2015,[23] neural network–based methods have increasingly replaced traditional statistical approaches, using semantic networks[24] and word embeddings to capture semantic properties of words.',
 'Intermediate tasks (e.g., part-of-speech tagging and dependency parsing) are not needed anymore.',
 'Neural machine translation, based on then-newly invented sequence-to-sequence transformations, made obsolete the intermediate steps, such as word alignment, previously necessary for statistical machine translation.',
 'The following is a list of some of the most commonly researched tasks in natural language processing.',
 'Some of these tasks have direct real-world applications, while others more commonly serve as subtasks that are used to aid in solving larger tasks.',
 'Though natural language processing tasks are closely intertwined, they can be subdivided into categories for convenience.',
 'A coarse division is given below.',
 'Based on long-standing trends in the field, it is possible to extrapolate future directions of NLP.',
 'As of 2020, three trends among the topics of the long-standing series of CoNLL Shared Tasks can be observed:[49]\nMost higher-level NLP applications involve aspects that emulate intelligent behavior and apparent comprehension of natural language.',
 'More broadly speaking, the technical operationalization of increasingly advanced aspects of cognitive behavior represents one of the developmental trajectories of NLP (see trends among CoNLL shared tasks above).',
 'Cognition refers to "the mental action or process of acquiring knowledge and understanding through thought, experience, and the senses.',
 '"[50] Cognitive science is the interdisciplinary, scientific study of the mind and its processes.',
 '[51] Cognitive linguistics is an interdisciplinary branch of linguistics, combining knowledge and research from both psychology and linguistics.',
 '[52] Especially during the age of symbolic NLP, the area of computational linguistics maintained strong ties with cognitive studies.',
 'As an example, George Lakoff offers a methodology to build natural language processing (NLP) algorithms through the perspective of cognitive science, along with the findings of cognitive linguistics,[53] with two defining aspects:\nTies with cognitive linguistics are part of the historical heritage of NLP, but they have been less frequently addressed since the statistical turn during the 1990s.',
 'Nevertheless, approaches to develop cognitive models towards technically operationalizable frameworks have been pursued in the context of various frameworks, e.g., of cognitive grammar,[56] functional grammar,[57] construction grammar,[58] computational psycholinguistics and cognitive neuroscience (e.g., ACT-R), however, with limited uptake in mainstream NLP (as measured by presence on major conferences[59] of the ACL).',
 'More recently, ideas of cognitive NLP have been revived as an approach to achieve explainability, e.g., under the notion of "cognitive AI".',
 '[60] Likewise, ideas of cognitive NLP are inherent to neural models multimodal NLP (although rarely made explicit)[61] and developments in artificial intelligence, specifically tools and technologies using large language model approaches[62] and new directions in artificial general intelligence based on the free energy principle[63] by British neuroscientist and theoretician at University College London Karl J. Friston.']

In [10]:
# remove punctuation and extra whitespaces and lowercase
for i in range(len(corpus )):
    corpus [i] = corpus [i].lower()
    corpus [i] = re.sub(r'\W',' ',corpus [i])
    corpus [i] = re.sub(r'\s+',' ',corpus [i])

In [11]:
corpus

['natural language processing nlp is the processing of natural language information by a computer ',
 'the study of nlp a subfield of computer science is generally associated with artificial intelligence ',
 'nlp is related to information retrieval knowledge representation computational linguistics and more broadly with linguistics ',
 ' 1 major processing tasks in an nlp system include speech recognition text classification natural language understanding and natural language generation ',
 'natural language processing has its roots in the 1950s ',
 ' 2 already in 1950 alan turing published an article titled computing machinery and intelligence which proposed what is now called the turing test as a criterion of intelligence though at the time that was not articulated as a problem separate from artificial intelligence ',
 'the proposed test includes a task that involves the automated interpretation and generation of natural language ',
 'the premise of symbolic nlp is well summarized by john searle s chinese room experiment given a collection of rules e g a chinese phrasebook with questions and matching answers the computer emulates natural language understanding or other nlp tasks by applying those rules to the data it confronts ',
 'up until the 1980s most natural language processing systems were based on complex sets of hand written rules ',
 'starting in the late 1980s however there was a revolution in natural language processing with the introduction of machine learning algorithms for language processing ',
 'this was due to both the steady increase in computational power see moore s law and the gradual lessening of the dominance of chomskyan theories of linguistics e g ',
 'transformational grammar whose theoretical underpinnings discouraged the sort of corpus linguistics that underlies the machine learning approach to language processing ',
 ' 9 symbolic approach i e the hand coding of a set of rules for manipulating symbols coupled with a dictionary lookup was historically the first approach used both by ai in general and by nlp in particular 19 20 such as by writing grammars or devising heuristic rules for stemming ',
 'machine learning approaches which include both statistical and neural networks on the other hand have many advantages over the symbolic approach rule based systems are commonly used in the late 1980s and mid 1990s the statistical approach ended a period of ai winter which was caused by the inefficiencies of the rule based approaches ',
 ' 21 22 the earliest decision trees producing systems of hard if then rules were still very similar to the old rule based approaches ',
 'only the introduction of hidden markov models applied to part of speech tagging announced the end of the old rule based approach ',
 'a major drawback of statistical methods is that they require elaborate feature engineering ',
 'since 2015 23 the statistical approach has been replaced by the neural networks approach using semantic networks 24 and word embeddings to capture semantic properties of words ',
 'intermediate tasks e g part of speech tagging and dependency parsing are not needed anymore ',
 'neural machine translation based on then newly invented sequence to sequence transformations made obsolete the intermediate steps such as word alignment previously necessary for statistical machine translation ',
 'the following is a list of some of the most commonly researched tasks in natural language processing ',
 'some of these tasks have direct real world applications while others more commonly serve as subtasks that are used to aid in solving larger tasks ',
 'though natural language processing tasks are closely intertwined they can be subdivided into categories for convenience ',
 'a coarse division is given below ',
 'based on long standing trends in the field it is possible to extrapolate future directions of nlp ',
 'as of 2020 three trends among the topics of the long standing series of conll shared tasks can be observed 47 most higher level nlp applications involve aspects that emulate intelligent behaviour and apparent comprehension of natural language ',
 'more broadly speaking the technical operationalization of increasingly advanced aspects of cognitive behaviour represents one of the developmental trajectories of nlp see trends among conll shared tasks above ',
 'cognition refers to the mental action or process of acquiring knowledge and understanding through thought experience and the senses ',
 ' 48 cognitive science is the interdisciplinary scientific study of the mind and its processes ',
 ' 49 cognitive linguistics is an interdisciplinary branch of linguistics combining knowledge and research from both psychology and linguistics ',
 ' 50 especially during the age of symbolic nlp the area of computational linguistics maintained strong ties with cognitive studies ',
 'as an example george lakoff offers a methodology to build natural language processing nlp algorithms through the perspective of cognitive science along with the findings of cognitive linguistics 51 with two defining aspects ties with cognitive linguistics are part of the historical heritage of nlp but they have been less frequently addressed since the statistical turn during the 1990s ',
 'nevertheless approaches to develop cognitive models towards technically operationalizable frameworks have been pursued in the context of various frameworks e g of cognitive grammar 54 functional grammar 55 construction grammar 56 computational psycholinguistics and cognitive neuroscience e g act r however with limited uptake in mainstream nlp as measured by presence on major conferences 57 of the acl ',
 'more recently ideas of cognitive nlp have been revived as an approach to achieve explainability e g under the notion of cognitive ai ',
 ' 58 likewise ideas of cognitive nlp are inherent to neural models multimodal nlp although rarely made explicit 59 and developments in artificial intelligence specifically tools and technologies using large language model approaches 60 and new directions in artificial general intelligence based on the free energy principle 61 by british neuroscientist and theoretician at university college london karl j friston ']

In [9]:
print(corpus[20])

The following is a list of some of the most commonly researched tasks in natural language processing.

### Step 2: Create a dictionary of word frequency

In [24]:
wordfreq = {}
for sentence in corpus:
    tokens = nltk.word_tokenize(sentence)
    for token in tokens:
        if token not in wordfreq.keys():
            wordfreq[token] = 1
        else:
            wordfreq[token] += 1

In [25]:
wordfreq

{'Natural': 2,
 'language': 16,
 'processing': 11,
 '(': 11,
 'NLP': 17,
 ')': 11,
 'is': 12,
 'the': 47,
 'of': 46,
 'natural': 11,
 'information': 2,
 'by': 9,
 'a': 14,
 'computer': 3,
 '.': 35,
 'subfield': 1,
 'science': 3,
 'and': 23,
 'closely': 2,
 'associated': 1,
 'with': 9,
 'artificial': 4,
 'intelligence': 5,
 'also': 1,
 'related': 1,
 'to': 13,
 'retrieval': 1,
 ',': 63,
 'knowledge': 3,
 'representation': 1,
 'computational': 4,
 'linguistics': 9,
 'more': 2,
 'broadly': 2,
 '[': 22,
 '1': 1,
 ']': 22,
 'Major': 1,
 'tasks': 8,
 'in': 15,
 'an': 5,
 'system': 1,
 'include': 2,
 ':': 7,
 'speech': 1,
 'recognition': 1,
 'text': 1,
 'classification': 1,
 'understanding': 3,
 'generation': 2,
 'has': 1,
 'its': 2,
 'roots': 1,
 '1950s': 1,
 '2': 1,
 'Already': 1,
 '1950': 1,
 'Alan': 1,
 'Turing': 2,
 'published': 1,
 'article': 1,
 'titled': 1,
 '``': 4,
 'Computing': 1,
 'Machinery': 1,
 'Intelligence': 1,
 "''": 2,
 'which': 3,
 'proposed': 2,
 'what': 1,
 'now': 1,
 'called': 1,
 'test': 2,
 'as': 7,
 'criterion': 1,
 'though': 1,
 'at': 2,
 'time': 1,
 'that': 6,
 'was': 5,
 'not': 2,
 'articulated': 1,
 'problem': 1,
 'separate': 1,
 'from': 2,
 'The': 4,
 'includes': 1,
 'task': 1,
 'involves': 1,
 'automated': 1,
 'interpretation': 1,
 'premise': 1,
 'symbolic': 3,
 'often': 1,
 'illustrated': 1,
 'using': 3,
 'John': 1,
 'Searle': 1,
 "'s": 2,
 'Chinese': 2,
 'room': 1,
 'thought': 2,
 'experiment': 1,
 'Given': 1,
 'collection': 1,
 'rules': 6,
 'e.g.': 5,
 'phrasebook': 1,
 'questions': 1,
 'matching': 1,
 'answers': 1,
 'emulates': 1,
 'or': 3,
 'other': 2,
 'applying': 1,
 'those': 1,
 'data': 1,
 'it': 2,
 'confronts': 1,
 'Up': 1,
 'until': 1,
 '1980s': 3,
 'most': 2,
 'systems': 3,
 'were': 2,
 'based': 3,
 'on': 6,
 'complex': 1,
 'sets': 1,
 'hand-written': 1,
 'Starting': 1,
 'late': 2,
 'however': 2,
 'there': 1,
 'revolution': 1,
 'introduction': 2,
 'machine': 3,
 'learning': 2,
 'algorithms': 2,
 'for': 5,
 'This': 1,
 'shift': 1,
 'influenced': 1,
 'increasing': 1,
 'power': 1,
 'see': 2,
 'Moore': 1,
 'law': 1,
 'decline': 1,
 'dominance': 1,
 'Chomskyan': 1,
 'linguistic': 1,
 'theories': 1,
 '...': 1,
 'e.g': 1,
 'transformational': 1,
 'grammar': 4,
 'whose': 1,
 'theoretical': 1,
 'underpinnings': 1,
 'discouraged': 1,
 'sort': 1,
 'corpus': 1,
 'underlies': 1,
 'machine-learning': 1,
 'approach': 7,
 '9': 1,
 'Symbolic': 1,
 'i.e.': 1,
 'hand-coding': 1,
 'set': 1,
 'manipulating': 1,
 'symbols': 1,
 'coupled': 1,
 'dictionary': 1,
 'lookup': 1,
 'historically': 1,
 'first': 1,
 'used': 3,
 'both': 3,
 'AI': 3,
 'general': 2,
 'particular': 1,
 '19': 1,
 '20': 1,
 'such': 2,
 'writing': 1,
 'grammars': 1,
 'devising': 1,
 'heuristic': 1,
 'stemming': 1,
 'Machine': 1,
 'approaches': 6,
 'statistical': 6,
 'neural': 3,
 'networks': 2,
 'hand': 1,
 'have': 6,
 'many': 1,
 'advantages': 1,
 'over': 1,
 'Rule-based': 1,
 'are': 6,
 'commonly': 3,
 'In': 1,
 'mid-1990s': 1,
 'ended': 1,
 'period': 1,
 'winter': 1,
 'caused': 1,
 'inefficiencies': 1,
 'rule-based': 3,
 '21': 1,
 '22': 1,
 'earliest': 1,
 'decision': 1,
 'trees': 1,
 'producing': 1,
 'hard': 1,
 'if–then': 1,
 'still': 1,
 'very': 1,
 'similar': 1,
 'old': 2,
 'Only': 1,
 'hidden': 1,
 'Markov': 1,
 'models': 3,
 'applied': 1,
 'part-of-speech': 2,
 'tagging': 2,
 'announced': 1,
 'end': 1,
 'A': 2,
 'major': 2,
 'drawback': 1,
 'methods': 2,
 'they': 3,
 'require': 1,
 'elaborate': 1,
 'feature': 1,
 'engineering': 1,
 'Since': 1,
 '2015': 1,
 '23': 1,
 'network–based': 1,
 'increasingly': 2,
 'replaced': 1,
 'traditional': 1,
 'semantic': 2,
 '24': 1,
 'word': 2,
 'embeddings': 1,
 'capture': 1,
 'properties': 1,
 'words': 1,
 'Intermediate': 1,
 'dependency': 1,
 'parsing': 1,
 'needed': 1,
 'anymore': 1,
 'Neural': 1,
 'translation': 2,
 'then-newly': 1,
 'invented': 1,
 'sequence-to-sequence': 1,
 'transformations': 1,
 'made': 2,
 'obsolete': 1,
 'intermediate': 1,
 'steps': 1,
 'alignment': 1,
 'previously': 1,
 'necessary': 1,
 'following': 1,
 'list': 1,
 'some': 1,
 'researched': 1,
 'Some': 1,
 'these': 1,
 'direct': 1,
 'real-world': 1,
 'applications': 2,
 'while': 1,
 'others': 1,
 'serve': 1,
 'subtasks': 1,
 'aid': 1,
 'solving': 1,
 'larger': 1,
 'Though': 1,
 'intertwined': 1,
 'can': 2,
 'be': 2,
 'subdivided': 1,
 'into': 1,
 'categories': 1,
 'convenience': 1,
 'coarse': 1,
 'division': 1,
 'given': 1,
 'below': 1,
 'Based': 1,
 'long-standing': 2,
 'trends': 3,
 'field': 1,
 'possible': 1,
 'extrapolate': 1,
 'future': 1,
 'directions': 2,
 'As': 2,
 '2020': 1,
 'three': 1,
 'among': 2,
 'topics': 1,
 'series': 1,
 'CoNLL': 2,
 'Shared': 1,
 'Tasks': 1,
 'observed': 1,
 '49': 1,
 'Most': 1,
 'higher-level': 1,
 'involve': 1,
 'aspects': 3,
 'emulate': 1,
 'intelligent': 1,
 'behavior': 2,
 'apparent': 1,
 'comprehension': 1,
 'More': 2,
 'speaking': 1,
 'technical': 1,
 'operationalization': 1,
 'advanced': 1,
 'cognitive': 11,
 'represents': 1,
 'one': 1,
 'developmental': 1,
 'trajectories': 1,
 'shared': 1,
 'above': 1,
 'Cognition': 1,
 'refers': 1,
 'mental': 1,
 'action': 1,
 'process': 1,
 'acquiring': 1,
 'through': 2,
 'experience': 1,
 'senses': 1,
 '50': 1,
 'Cognitive': 2,
 'interdisciplinary': 2,
 'scientific': 1,
 'study': 1,
 'mind': 1,
 'processes': 1,
 '51': 1,
 'branch': 1,
 'combining': 1,
 'research': 1,
 'psychology': 1,
 '52': 1,
 'Especially': 1,
 'during': 2,
 'age': 1,
 'area': 1,
 'maintained': 1,
 'strong': 1,
 'ties': 1,
 'studies': 1,
 'example': 1,
 'George': 1,
 'Lakoff': 1,
 'offers': 1,
 'methodology': 1,
 'build': 1,
 'perspective': 1,
 'along': 1,
 'findings': 1,
 '53': 1,
 'two': 1,
 'defining': 1,
 'Ties': 1,
 'part': 1,
 'historical': 1,
 'heritage': 1,
 'but': 1,
 'been': 3,
 'less': 1,
 'frequently': 1,
 'addressed': 1,
 'since': 1,
 'turn': 1,
 '1990s': 1,
 'Nevertheless': 1,
 'develop': 1,
 'towards': 1,
 'technically': 1,
 'operationalizable': 1,
 'frameworks': 2,
 'pursued': 1,
 'context': 1,
 'various': 1,
 '56': 1,
 'functional': 1,
 '57': 1,
 'construction': 1,
 '58': 1,
 'psycholinguistics': 1,
 'neuroscience': 1,
 'ACT-R': 1,
 'limited': 1,
 'uptake': 1,
 'mainstream': 1,
 'measured': 1,
 'presence': 1,
 'conferences': 1,
 '59': 1,
 'ACL': 1,
 'recently': 1,
 'ideas': 2,
 'revived': 1,
 'achieve': 1,
 'explainability': 1,
 'under': 1,
 'notion': 1,
 '60': 1,
 'Likewise': 1,
 'inherent': 1,
 'multimodal': 1,
 'although': 1,
 'rarely': 1,
 'explicit': 1,
 '61': 1,
 'developments': 1,
 'specifically': 1,
 'tools': 1,
 'technologies': 1,
 'large': 1,
 'model': 1,
 '62': 1,
 'new': 1,
 'free': 1,
 'energy': 1,
 'principle': 1,
 '63': 1,
 'British': 1,
 'neuroscientist': 1,
 'theoretician': 1,
 'University': 1,
 'College': 1,
 'London': 1,
 'Karl': 1,
 'J.': 1,
 'Friston': 1}

In [26]:
len(wordfreq)

457

### Remove the least frequent words using heapq library

In [12]:
import heapq
most_freq = heapq.nlargest(200, wordfreq, key=wordfreq.get)

In [27]:
most_freq

[',',
 'the',
 'of',
 '.',
 'and',
 '[',
 ']',
 'NLP',
 'language',
 'in',
 'a',
 'to',
 'is',
 'processing',
 '(',
 ')',
 'natural',
 'cognitive',
 'by',
 'with',
 'linguistics',
 'tasks',
 ':',
 'as',
 'approach',
 'that',
 'rules',
 'on',
 'approaches',
 'statistical',
 'have',
 'are',
 'intelligence',
 'an',
 'was',
 'e.g.',
 'for',
 'artificial',
 'computational',
 '``',
 'The',
 'grammar',
 'computer',
 'science',
 'knowledge',
 'understanding',
 'which',
 'symbolic',
 'using',
 'or',
 '1980s',
 'systems',
 'based',
 'machine',
 'used',
 'both',
 'AI',
 'neural',
 'commonly',
 'rule-based',
 'models',
 'they',
 'trends',
 'aspects',
 'been',
 'Natural',
 'information',
 'closely',
 'more',
 'broadly',
 'include',
 'generation',
 'its',
 'Turing',
 "''",
 'proposed',
 'test',
 'at',
 'not',
 'from',
 "'s",
 'Chinese',
 'thought',
 'other',
 'it',
 'most',
 'were',
 'late',
 'however',
 'introduction',
 'learning',
 'algorithms',
 'see',
 'general',
 'such',
 'networks',
 'old',
 'part-of-speech',
 'tagging',
 'A',
 'major',
 'methods',
 'increasingly',
 'semantic',
 'word',
 'translation',
 'made',
 'applications',
 'can',
 'be',
 'long-standing',
 'directions',
 'As',
 'among',
 'CoNLL',
 'behavior',
 'More',
 'through',
 'Cognitive',
 'interdisciplinary',
 'during',
 'frameworks',
 'ideas',
 'subfield',
 'associated',
 'also',
 'related',
 'retrieval',
 'representation',
 '1',
 'Major',
 'system',
 'speech',
 'recognition',
 'text',
 'classification',
 'has',
 'roots',
 '1950s',
 '2',
 'Already',
 '1950',
 'Alan',
 'published',
 'article',
 'titled',
 'Computing',
 'Machinery',
 'Intelligence',
 'what',
 'now',
 'called',
 'criterion',
 'though',
 'time',
 'articulated',
 'problem',
 'separate',
 'includes',
 'task',
 'involves',
 'automated',
 'interpretation',
 'premise',
 'often',
 'illustrated',
 'John',
 'Searle',
 'room',
 'experiment',
 'Given',
 'collection',
 'phrasebook',
 'questions',
 'matching',
 'answers',
 'emulates',
 'applying',
 'those',
 'data',
 'confronts',
 'Up',
 'until',
 'complex',
 'sets',
 'hand-written',
 'Starting',
 'there',
 'revolution',
 'This',
 'shift',
 'influenced',
 'increasing',
 'power',
 'Moore',
 'law',
 'decline',
 'dominance',
 'Chomskyan',
 'linguistic']

### Step 3: Create Bag of Words Model

In [28]:
sentence_vectors = []
most_freq = list(most_freq)
most_freq_set = set(most_freq)

for sentence in corpus:
    # Tokenize and keep only relevant words (intersection)
    tokens = set(nltk.word_tokenize(sentence)) & most_freq_set

    # Binary vector: 1 if word present, else 0
    sent_vec = [1 if word in tokens else 0 for word in most_freq]

    sentence_vectors.append(sent_vec)

### Convert it to numpy array

In [29]:
sentence_vectors = np.asarray(sentence_vectors)

In [30]:
sentence_vectors

array([[0, 1, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], shape=(35, 200))

### Better visualization ?

In [31]:
import pandas as pd
pd.DataFrame(sentence_vectors, columns=most_freq)

,",",the,of,.,and,[,],NLP,language,in,...,shift,influenced,increasing,power,Moore,law,decline,dominance,Chomskyan,linguistic
0,0,1,1,1,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,1,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
5,1,1,1,1,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,0,1,1,1,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7,1,1,1,1,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
8,1,1,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9,1,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
10,0,1,1,1,1,0,0,0,0,1,...,1,1,1,1,1,1,1,1,1,1
11,1,1,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
12,1,1,1,1,1,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
13,1,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,1,1,1,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,1,0,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,1,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
21,1,0,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
22,1,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,1,1,1,1,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
25,1,1,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
26,1,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
27,1,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,1,1,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,1,0,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,1,1,1,1,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
31,1,1,1,1,0,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
32,1,1,1,1,1,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
33,1,1,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
34,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0



---

## Implementation using Sklearn CountVectorizer

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

In [33]:
# Step 1: Initialize CountVectorizer with top 200 most frequent words only
vectorizer = CountVectorizer(
    max_features=200,
    # stop_words='english',
    # token_pattern=r'\b[a-zA-Z]+\b'
)

In [34]:
# Step 2: Fit and transform corpus
X = vectorizer.fit_transform(corpus)

In [35]:
# Step 3: Get feature names (vocabulary)
vocab = vectorizer.get_feature_names_out()
vocab

array(['19', '1980s', '1990s', 'ai', 'algorithms', 'among', 'an', 'and',
       'applications', 'approach', 'approaches', 'are', 'artificial',
       'as', 'aspects', 'at', 'based', 'be', 'been', 'behavior', 'both',
       'broadly', 'by', 'can', 'chinese', 'closely', 'cognitive',
       'commonly', 'computational', 'computer', 'conll', 'directions',
       'during', 'for', 'frameworks', 'from', 'general', 'generation',
       'given', 'grammar', 'hand', 'have', 'however', 'ideas', 'in',
       'include', 'increasingly', 'information', 'intelligence',
       'interdisciplinary', 'intermediate', 'introduction', 'is', 'it',
       'its', 'knowledge', 'language', 'late', 'learning', 'linguistics',
       'long', 'machine', 'made', 'major', 'methods', 'models', 'more',
       'most', 'natural', 'network', 'networks', 'neural', 'neuroscience',
       'neuroscientist', 'nevertheless', 'new', 'newly', 'nlp', 'not',
       'notion', 'now', 'observed', 'obsolete', 'of', 'offers', 'often',
       'old', 'on', 'one', 'only', 'operationalizable',
       'operationalization', 'or', 'other', 'others', 'over', 'parsing',
       'part', 'particular', 'period', 'perspective', 'phrasebook',
       'possible', 'power', 'premise', 'presence', 'previously',
       'principle', 'problem', 'process', 'processes', 'processing',
       'producing', 'properties', 'proposed', 'psycholinguistics',
       'psychology', 'published', 'pursued', 'questions', 'rarely',
       'real', 'recently', 'rule', 'rules', 'science', 'see', 'semantic',
       'sequence', 'shared', 'since', 'some', 'speech', 'standing',
       'statistical', 'such', 'symbolic', 'systems', 'tagging', 'tasks',
       'technical', 'technically', 'technologies', 'test', 'text', 'that',
       'the', 'then', 'theoretical', 'theoretician', 'theories', 'there',
       'these', 'they', 'this', 'those', 'though', 'thought', 'three',
       'through', 'ties', 'time', 'titled', 'to', 'tools', 'topics',
       'towards', 'traditional', 'trajectories', 'transformational',
       'transformations', 'translation', 'trees', 'trends', 'turing',
       'turn', 'two', 'under', 'underlies', 'underpinnings',
       'understanding', 'university', 'until', 'up', 'uptake', 'used',
       'using', 'various', 'very', 'was', 'were', 'what', 'which',
       'while', 'whose', 'winter', 'with', 'word', 'words', 'world'],
      dtype=object)

In [36]:
# Step 4: Convert BoW matrix to a pandas DataFrame
bow_df = pd.DataFrame(X.toarray(), columns=vocab)
bow_df.head()

,19,1980s,1990s,ai,algorithms,among,an,and,applications,approach,...,were,what,which,while,whose,winter,with,word,words,world
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [37]:
print("Words in vocab but not in most_freq:", set(vocab) - set(most_freq))
print("Words in most_freq but not in vocab:", set(most_freq) - set(vocab))

Words in vocab but not in most_freq: {'offers', 'new', 'university', 'operationalizable', 'processes', 'recently', 'trajectories', 'psychology', 'particular', 'then', 'pursued', 'principle', 'technically', 'technical', 'two', 'whose', 'period', 'over', 'newly', 'turn', 'one', 'conll', 'these', 'uptake', 'network', 'obsolete', 'rarely', 'psycholinguistics', 'ai', 'underlies', 'theoretician', 'words', 'rule', 'intermediate', 'properties', '19', 'previously', 'possible', 'tools', 'traditional', 'world', 'theoretical', 'topics', 'underpinnings', 'under', 'various', 'shared', 'others', 'since', 'ties', 'technologies', 'transformations', 'perspective', 'trees', 'neuroscientist', 'sequence', 'this', 'presence', 'hand', 'operationalization', 'nlp', 'towards', 'while', 'parsing', 'long', 'up', 'turing', 'only', '1990s', 'very', 'some', 'notion', 'nevertheless', 'theories', 'three', 'transformational', 'chinese', 'neuroscience', 'observed', 'process', 'producing', 'real', 'given', 'part', 'standing', 'winter'}
Words in most_freq but not in vocab: {'Already', "''", '1950s', 'dominance', 'Major', 'Computing', 'a', '[', 'revolution', 'Cognitive', 'Chomskyan', '1', 'recognition', 'related', 'A', 'retrieval', 'includes', 'Machinery', 'Alan', 'part-of-speech', 'applying', 'law', 'shift', 'confronts', 'Moore', '(', 'This', 'Starting', 'Searle', 'More', '``', 'illustrated', 'Turing', 'representation', 'e.g.', 'The', 'Given', 'complex', 'AI', 'CoNLL', 'decline', 'roots', 'article', 'system', 'linguistic', 'interpretation', 'has', ')', 'influenced', 'Chinese', '1950', 'experiment', 'rule-based', "'s", 'associated', 'data', '2', 'long-standing', 'collection', 'answers', 'articulated', 'hand-written', 'task', 'automated', 'sets', 'separate', 'called', 'classification', ':', 'Intelligence', 'room', 'NLP', ',', 'criterion', 'John', 'increasing', 'also', 'As', ']', 'matching', 'emulates', 'involves', 'Up', '.', 'Natural', 'subfield'}