**Download necessary files**

In [1]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /Users/user/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /Users/user/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

**Import the necessary libraries**

In [2]:
import numpy as np
import random
import string

**Import libraries for scraping - beautifulSoup**

In [3]:
from bs4 import BeautifulSoup
import urllib.request
import re

**Read the web link**

In [4]:
# Define URL and headers (pretend to be a real browser)
url = "https://en.wikipedia.org/wiki/Natural_language_processing"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

# Create a request object with headers
req = urllib.request.Request(url, headers=headers)

# Open and read the page
with urllib.request.urlopen(req) as response:
    raw_html = response.read()

raw_html[:500]

b'<!DOCTYPE html>\n<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25easte'

**Convert the web link contents into a file**

In [5]:
# Parse the HTML using BeautifulSoup
article_html = BeautifulSoup(raw_html, "lxml")

**Find only the html text containing inside < p > tags**

In [6]:
# Extract all paragraph tags
article_paragraphs = article_html.find_all("p")

**Read all the text inside paragraphs**

In [7]:
# Combine all text into one string
article_text = ""
for para in article_paragraphs:
    article_text += para.get_text()

article_text[:500]

'\nNatural language processing (NLP) is the processing of natural language information by a computer. NLP is a subfield of computer science and is closely associated with artificial intelligence. NLP is also related to information retrieval, knowledge representation, computational linguistics, and linguistics more broadly.[1]\nMajor processing tasks in an NLP system include: speech recognition, text classification, natural language understanding, and natural language generation.\nNatural language pr'

**Split the sentences**

In [8]:
corpus = nltk.sent_tokenize(article_text)
corpus

['\nNatural language processing (NLP) is the processing of natural language information by a computer.',
 'NLP is a subfield of computer science and is closely associated with artificial intelligence.',
 'NLP is also related to information retrieval, knowledge representation, computational linguistics, and linguistics more broadly.',
 '[1]\nMajor processing tasks in an NLP system include: speech recognition, text classification, natural language understanding, and natural language generation.',
 'Natural language processing has its roots in the 1950s.',
 '[2] Already in 1950, Alan Turing published an article titled "Computing Machinery and Intelligence" which proposed what is now called the Turing test as a criterion of intelligence, though at the time that was not articulated as a problem separate from artificial intelligence.',
 'The proposed test includes a task that involves the automated interpretation and generation of natural language.',
 "The premise of symbolic NLP is often illustrated using John Searle's Chinese room thought experiment: Given a collection of rules (e.g., a Chinese phrasebook, with questions and matching answers), the computer emulates natural language understanding (or other NLP tasks) by applying those rules to the data it confronts.",
 'Up until the 1980s, most natural language processing systems were based on complex sets of hand-written rules.',
 'Starting in the late 1980s, however, there was a revolution in natural language processing with the introduction of machine learning algorithms for language processing.',
 "This shift was influenced by increasing computational power (see Moore's law) and a decline in the dominance of Chomskyan linguistic theories... (e.g.",
 'transformational grammar), whose theoretical underpinnings discouraged the sort of corpus linguistics that underlies the machine-learning approach to language processing.',
 '[9]\nSymbolic approach, i.e., the hand-coding of a set of rules for manipulating symbols, coupled with a dictionary lookup, was historically the first approach used both by AI in general and by NLP in particular:[19][20] such as by writing grammars or devising heuristic rules for stemming.',
 'Machine learning approaches, which include both statistical and neural networks, on the other hand, have many advantages over the symbolic approach:\nRule-based systems are commonly used:\nIn the late 1980s and mid-1990s, the statistical approach ended a period of AI winter, which was caused by the inefficiencies of the rule-based approaches.',
 '[21][22]\nThe earliest decision trees, producing systems of hard if–then rules, were still very similar to the old rule-based approaches.',
 'Only the introduction of hidden Markov models, applied to part-of-speech tagging, announced the end of the old rule-based approach.',
 'A major drawback of statistical methods is that they require elaborate feature engineering.',
 'Since 2015,[23] neural network–based methods have increasingly replaced traditional statistical approaches, using semantic networks[24] and word embeddings to capture semantic properties of words.',
 'Intermediate tasks (e.g., part-of-speech tagging and dependency parsing) are not needed anymore.',
 'Neural machine translation, based on then-newly invented sequence-to-sequence transformations, made obsolete the intermediate steps, such as word alignment, previously necessary for statistical machine translation.',
 'The following is a list of some of the most commonly researched tasks in natural language processing.',
 'Some of these tasks have direct real-world applications, while others more commonly serve as subtasks that are used to aid in solving larger tasks.',
 'Though natural language processing tasks are closely intertwined, they can be subdivided into categories for convenience.',
 'A coarse division is given below.',
 'Based on long-standing trends in the field, it is possible to extrapolate future directions of NLP.',
 'As of 2020, three trends among the topics of the long-standing series of CoNLL Shared Tasks can be observed:[49]\nMost higher-level NLP applications involve aspects that emulate intelligent behavior and apparent comprehension of natural language.',
 'More broadly speaking, the technical operationalization of increasingly advanced aspects of cognitive behavior represents one of the developmental trajectories of NLP (see trends among CoNLL shared tasks above).',
 'Cognition refers to "the mental action or process of acquiring knowledge and understanding through thought, experience, and the senses.',
 '"[50] Cognitive science is the interdisciplinary, scientific study of the mind and its processes.',
 '[51] Cognitive linguistics is an interdisciplinary branch of linguistics, combining knowledge and research from both psychology and linguistics.',
 '[52] Especially during the age of symbolic NLP, the area of computational linguistics maintained strong ties with cognitive studies.',
 'As an example, George Lakoff offers a methodology to build natural language processing (NLP) algorithms through the perspective of cognitive science, along with the findings of cognitive linguistics,[53] with two defining aspects:\nTies with cognitive linguistics are part of the historical heritage of NLP, but they have been less frequently addressed since the statistical turn during the 1990s.',
 'Nevertheless, approaches to develop cognitive models towards technically operationalizable frameworks have been pursued in the context of various frameworks, e.g., of cognitive grammar,[56] functional grammar,[57] construction grammar,[58] computational psycholinguistics and cognitive neuroscience (e.g., ACT-R), however, with limited uptake in mainstream NLP (as measured by presence on major conferences[59] of the ACL).',
 'More recently, ideas of cognitive NLP have been revived as an approach to achieve explainability, e.g., under the notion of "cognitive AI".',
 '[60] Likewise, ideas of cognitive NLP are inherent to neural models multimodal NLP (although rarely made explicit)[61] and developments in artificial intelligence, specifically tools and technologies using large language model approaches[62] and new directions in artificial general intelligence based on the free energy principle[63] by British neuroscientist and theoretician at University College London Karl J. Friston.']

**Clean the text**

In [9]:
for i in range(len(corpus )):
    corpus [i] = corpus [i].lower()
    corpus [i] = re.sub(r'\W',' ',corpus [i])
    corpus [i] = re.sub(r'\s+',' ',corpus [i])

**Create a dictionary of word frequency**

In [10]:
wordfreq = {}
for sentence in corpus:
    tokens = nltk.word_tokenize(sentence)
    for token in tokens:
        if token not in wordfreq.keys():
            wordfreq[token] = 1
        else:
            wordfreq[token] += 1

**Filter the top 200 words**

In [11]:
import heapq
most_freq = heapq.nlargest(200, wordfreq, key=wordfreq.get)

### TF-IDF Formula
IDF (Inverse Document Frequency)
```
IDF(term) = log(N / (1 + n_term))
```

*  N = total number of documents
*  n_term = number of documents that contain the term
*  1 + avoids division by zero

TF-IDF
```
TFIDF(term, doc) = TF(term, doc) * IDF(term)
```

*  TF(term, doc) = count of the term in that document (or normalized count)
*  IDF(term) = from the IDF formula above

**Compute IDF values**

In [12]:
word_idf_values = {}
for token in most_freq:
    doc_containing_word = 0
    for document in corpus:
        if token in nltk.word_tokenize(document):
            doc_containing_word += 1
    word_idf_values[token] = np.log(len(corpus)/(1 + doc_containing_word))

**Compute TF values**

In [13]:
word_tf_values = {}
for token in most_freq:
    sent_tf_vector = []
    for document in corpus:
        doc_freq = 0
        for word in nltk.word_tokenize(document):
            if token == word:
                  doc_freq += 1
        word_tf = doc_freq/len(nltk.word_tokenize(document))
        sent_tf_vector.append(word_tf)
    word_tf_values[token] = sent_tf_vector

**Compute TF-IDF values**

In [14]:
tfidf_values = []
for token in word_tf_values.keys():
    tfidf_sentences = []
    for tf_sentence in word_tf_values[token]:
        tf_idf_score = tf_sentence * word_idf_values[token]
        tfidf_sentences.append(tf_idf_score)
    tfidf_values.append(tfidf_sentences)

In [15]:
tf_idf_model = np.asarray(tfidf_values)

In [16]:
tf_idf_model = np.transpose(tf_idf_model)

In [17]:
tf_idf_model

array([[0.02123225, 0.01101076, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.01101076, 0.04749831, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.04433175, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.01025005, 0.00797331, 0.01146511, ..., 0.        , 0.        ,
        0.        ],
       [0.01292398, 0.01340441, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00503816, 0.00261272, 0.04508314, ..., 0.        , 0.        ,
        0.        ]], shape=(35, 200))

In [18]:
import pandas as pd
pd.DataFrame(tf_idf_model, columns=most_freq)

,the,of,and,nlp,language,a,in,to,natural,cognitive,...,decline,dominance,chomskyan,linguistic,theories,transformational,whose,theoretical,underpinnings,discouraged
0,0.021232,0.011011,0.000000,0.060521,0.130899,0.065449,0.000000,0.000000,0.152920,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
1,0.000000,0.011011,0.047498,0.060521,0.000000,0.065449,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
2,0.000000,0.000000,0.044332,0.056487,0.000000,0.000000,0.000000,0.056487,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
3,0.000000,0.000000,0.033249,0.042365,0.091629,0.000000,0.049520,0.000000,0.107044,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
4,0.033028,0.000000,0.000000,0.000000,0.101810,0.000000,0.110044,0.000000,0.118938,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
5,0.013826,0.003585,0.015465,0.000000,0.000000,0.042618,0.023033,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
6,0.037156,0.009634,0.041561,0.000000,0.057268,0.057268,0.000000,0.000000,0.066903,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
7,0.017835,0.006166,0.013300,0.033892,0.018326,0.036652,0.000000,0.016946,0.021409,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
8,0.016514,0.008564,0.000000,0.000000,0.050905,0.000000,0.000000,0.000000,0.059469,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
9,0.024771,0.006423,0.000000,0.000000,0.076358,0.038179,0.082533,0.000000,0.044602,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
10,0.012385,0.006423,0.027707,0.000000,0.000000,0.038179,0.041267,0.000000,0.000000,0.000000,...,0.119258,0.119258,0.119258,0.119258,0.119258,0.00000,0.00000,0.00000,0.00000,0.00000
11,0.029725,0.007708,0.000000,0.000000,0.045815,0.000000,0.000000,0.042365,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.14311,0.14311,0.14311,0.14311,0.14311
12,0.011890,0.006166,0.013300,0.016946,0.000000,0.036652,0.039616,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
13,0.033028,0.005709,0.024629,0.000000,0.000000,0.016968,0.018341,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
14,0.025848,0.006702,0.000000,0.000000,0.000000,0.000000,0.000000,0.036839,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
15,0.040534,0.021021,0.000000,0.000000,0.000000,0.000000,0.000000,0.038514,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
16,0.000000,0.011858,0.000000,0.000000,0.000000,0.070484,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
17,0.000000,0.005929,0.025576,0.000000,0.000000,0.000000,0.000000,0.032588,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
18,0.000000,0.010277,0.044332,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
19,0.011009,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.031381,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
20,0.034971,0.018135,0.000000,0.000000,0.053899,0.053899,0.058259,0.000000,0.062967,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
21,0.000000,0.006166,0.000000,0.000000,0.000000,0.000000,0.039616,0.033892,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
22,0.000000,0.000000,0.000000,0.000000,0.057268,0.000000,0.000000,0.000000,0.066903,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
23,0.000000,0.000000,0.000000,0.000000,0.000000,0.152715,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
24,0.017485,0.009068,0.000000,0.049841,0.000000,0.000000,0.058259,0.049841,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
25,0.015645,0.016226,0.017499,0.022297,0.024113,0.000000,0.000000,0.000000,0.028170,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
26,0.021232,0.022022,0.000000,0.030261,0.000000,0.000000,0.000000,0.000000,0.000000,0.048504,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
27,0.031290,0.008113,0.069998,0.000000,0.000000,0.000000,0.000000,0.044595,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
28,0.042465,0.011011,0.047498,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.097009,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
29,0.000000,0.008564,0.073886,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.075451,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
30,0.031290,0.016226,0.000000,0.044595,0.000000,0.000000,0.000000,0.000000,0.000000,0.071480,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
31,0.025191,0.010451,0.000000,0.028722,0.015530,0.015530,0.000000,0.014361,0.018143,0.069057,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
32,0.010250,0.007973,0.011465,0.014609,0.000000,0.000000,0.034152,0.014609,0.000000,0.070248,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
33,0.012924,0.013404,0.000000,0.036839,0.000000,0.000000,0.000000,0.036839,0.000000,0.118098,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000
34,0.005038,0.002613,0.045083,0.028722,0.015530,0.000000,0.033573,0.014361,0.000000,0.023019,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.00000,0.00000,0.00000



---

## Implementation using Sklearn TfidfVectorizer

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [23]:
# Step 1: Initialize TF-IDF vectorizer
vectorizer = TfidfVectorizer(
    max_features=200,            # limit vocab to top 200 most frequent words
    # stop_words='english',        # remove common English stopwords
    # token_pattern=r'\b[a-zA-Z]+\b',  # keep alphabetic words only (ignore numbers)
    # lowercase=True
)

In [24]:
# Step 2: Fit and transform the corpus
X = vectorizer.fit_transform(corpus)

In [25]:
# Step 3: Convert to DataFrame for readability
tfidf_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
tfidf_df.head()

,19,1980s,1990s,ai,algorithms,among,an,and,applications,approach,...,were,what,which,while,whose,winter,with,word,words,world
0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.183970,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.272082,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.171311,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.243009,0.147380,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0